hubblestack/hubble

.gitignore, hubble/daemon.py, setup.py
=> Fix install location and init script for amazon linux

.gitignore, pkg/specs/hubblestack-el7.spec
Nothing automated about this yet, you have to package up the source tarball manually.
=> Add initial spec file for cent7

hubblestack/files/hubblestack_nova/cve_scan_v2.py
Ref https://github.com/hubblestack/nova/pull/299
=> Fix for Debian systems which have an int for os_version

hubblestack/extmods/modules/nebula_osquery.py
https://github.com/hubblestack/nebula/pull/33
=> Add uptime fallback query

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
- Turn off http_event_collector_debug everywhere
- Add aws information to events
- Fix for blank hosts when fqdn doesn't return anything
=> Updates from upstream hubble-salt

hubblestack/extmods/modules/pulsar.py
https://github.com/hubblestack/hubble-salt/pull/56
=> Always load pulsar, fail silently

hubblestack/extmods/returners/aws_details.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
On azure machine, it's trying to populate aws data, this needs to be fixed.
=> Fixing aws details issues for azure machine

pkg/scripts/osquery-build.sh, pkg/scripts/pip-install.sh, pkg/scripts/pyinstaller-requirements-debian7.txt
- Skip pygit2
- Fix ncurses linking in osquery install
=> Fix build_debs for debian 7

hubblestack/extmods/fileserver/azurefs.py, hubblestack/extmods/modules/nebula_osquery.py
=> Add azurefs

hubblestack/extmods/modules/nebula_osquery.py
Refs https://github.com/hubblestack/hubble-salt/pull/67
=> Remove deprecated --read_user_max flag

hubblestack/extmods/modules/nebula_osquery.py, hubblestack/files/hubblestack_nova/win_auditpol.py, hubblestack/files/hubblestack_nova/win_firewall.py, hubblestack/files/hubblestack_nova/win_gp.py, hubblestack/files/hubblestack_nova/win_pkg.py, hubblestack/files/hubblestack_nova/win_reg.py, hubblestack/files/hubblestack_nova/win_secedit.py, pkg/scripts/pyinstaller-requirements.txt
Many module fixes to account for false readings on the nova section of hubble.  Fixed a lot of logic errors, and added a few things to account for answers in the CIS yaml.
=> Windows fixes

hubblestack/extmods/modules/win_pulsar.py
Changed the powershell command to use something less intensive, then had to change what was returned since not all items were the same
=> CPU utilization improvement for win_pulsar

hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
I noticed these copypasta errors while I was code-diving.
=> copypasta error in splunk returners

hubblestack/extmods/returners/logstash_nebula_return.py, hubblestack/extmods/returners/logstash_nova_return.py, hubblestack/extmods/returners/logstash_pulsar_return.py
Updating from using PUT to POST.
=> changing from requests.put to requests.post

hubblestack/extmods/modules/pulsar.py, hubblestack/extmods/modules/win_pulsar.py, hubblestack/extmods/returners/splunk_pulsar_return.py
=> Adding pulsar config name in splunk data

hubblestack/extmods/modules/nebula_osquery.py
Fixes https://github.com/hubblestack/hubble/issues/98
=> Process nebula results with `__JSONIFY__` through json

pkg/hubble.freebsd
I'd like to get this included in an effort to get FreeBSD supported
=> Freebsd pkg startup script

conf/hubble, hubblestack/daemon.py, hubblestack/extmods/modules/pulsar.py
Fixes https://github.com/hubblestack/hubble/issues/99
=> Add canary FIM events

hubblestack/extmods/modules/win_pulsar.py
Ref https://github.com/hubblestack/hubble/pull/125
=> Add pulsar.canary to win_pulsar as well

hubblestack/extmods/modules/nebula_osquery.py
=> Add `custom_` prefix to nebula.fields

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
Also hard code a few fields that we know would be useful.
Ref: https://dev.splunk.com/view/event-collector/SP-CAAAFB6
=> Add option to extract fields at index time in Splunk returners

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/amazonlinux2017.03/Dockerfile, pkg/amazonlinux2017.03/pyinstaller-requirements.txt, pkg/centos7/Dockerfile, pkg/centos7/pyinstaller-requirements.txt, pkg/coreos/Dockerfile, pkg/coreos/pyinstaller-requirements.txt, pkg/debian8/Dockerfile, pkg/debian8/pyinstaller-requirements.txt, pkg/debian9/Dockerfile, pkg/debian9/pyinstaller-requirements.txt, pkg/hubble, pkg/hubble.service
images from these dockerfiles are over 4.5 Gb per image.
=> Fossam dockeromnibus

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile
=> Separate HUBBLE_VERSION and HUBBLE_CHECKOUT

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
I made a mistake here. This should work.
=> Fix index-time extraction logic

pkg/centos6/Dockerfile, pkg/centos6/pyinstaller-requirements.txt
These Dockerfiles took more work
=> Fossam-dockerline

hubblestack/files/hubblestack_nova/grep.py, pkg/debian8/Dockerfile
Also fix typo in deb8 dockerfile
=> Add match_output_multiline to grep nova module

hubblestack/files/hubblestack_nova/misc.py
Adding more functions to misc.py
Ignoring error code returned
Updated check_all_ports_firewall_rules function
=> Adding more functions to misc.py

hubblestack/extmods/modules/nova_loader.py, pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile
Also remove extraneous deb arguments from rpm fpm commands
=> Add more error logging

pkg/debian7/Dockerfile, pkg/debian7/pyinstaller-requirements.txt, pkg/debian8/Dockerfile, pkg/debian8/pyinstaller-requirements.txt
Two items in these commits covered:
* Dockerfile for debian 7
* working pygit2 in debian 8 package
=> Fossam dockerwork

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile
This PR should get pygit2 working again everywhere except coreos.
=> pygit2 fixes, minor comment wording changes

hubblestack/daemon.py, hubblestack/files/hubblestack_nova/misc.py
Also remove troublesome boto modules so they don't give us error logs we don't care about.
=> Fix misc.py to move on in the event of errors

README.md, conf/hubble
Instructions about release packages and local FS profile
=> Documentation

hubblestack/files/hubblestack_nova/misc.py
Adding more functions in misc module
=> Adding new functions in misc module

hubblestack/files/hubblestack_nova/misc.py
=> Update few misc functions

hubblestack/files/hubblestack_nova/mount.py, hubblestack/files/hubblestack_nova/systemctl.py
* Adding mount and systemctl modules for hubble
=> Adding mount and systemctl modules

conf/hubble, hubblestack/daemon.py, hubblestack/splunklogging.py
Turned off by default, have to set `hubblestack:splunklogging` to True. Uses the existing splunk returner config.
=> Add splunk log handler

hubblestack/files/hubblestack_nova/misc.py, hubblestack/files/hubblestack_nova/stat_nova.py, hubblestack/files/hubblestack_nova/sysctl.py
* Updating stat_nova module and added some new misc functions
=> Updating stat_nova module and added some new misc functions

hubblestack/extmods/modules/nebula_osquery.py
=> Better error handling for failed queries

hubblestack/daemon.py
Added a check for windows so that daemon.py could insert defaults for windows or linux depending on the OS.
=> Added Windows defaults to daemon.py 

pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/dev/amazonlinux2017.03/Dockerfile, pkg/dev/amazonlinux2017.03/pyinstaller-requirements.txt, pkg/dev/centos6/Dockerfile, pkg/dev/centos6/pyinstaller-requirements.txt, pkg/dev/centos7/Dockerfile, pkg/dev/centos7/pyinstaller-requirements.txt, pkg/dev/coreos/Dockerfile, pkg/dev/coreos/pyinstaller-requirements.txt, pkg/dev/debian7/Dockerfile, pkg/dev/debian7/pyinstaller-requirements.txt, pkg/dev/debian8/Dockerfile, pkg/dev/debian8/pyinstaller-requirements.txt, pkg/dev/debian9/Dockerfile, pkg/dev/debian9/pyinstaller-requirements.txt
I put it in its own directory to make merging between develop/master
less nightmarish.
Only four lines actually changed. If you look at the second commit, you can see that diff much more easily than looking at the entire PR diff.
=> Add dev packaging

hubblestack/files/hubblestack_nova/misc.py
Consider PR 
https://github.com/hubblestack/hubblestack_data/pull/87 
for illustration of these changes.
=> Making changes in misc.py to take some value as arguements

hubblestack/files/hubblestack_nova/win_firewall.py
this allows for an extra value in the yaml that will determine if the value must be equal or can be greater than or less than.  match_type
=> Adding the ability to parse match_type

hubblestack/files/hubblestack_nova/systemctl.py
Tiny change to systemctl docs. Fixes hubblestack/hubble/issues/262
=> Small doc fix

hubblestack/files/hubblestack_nova/win_firewall.py, utils/win_yaml_updater.py
fixed yaml updater to not overwrite module sections when running.  Added 2008 exception to win_firewall
=> win_yaml_updater.py fix, and 2008 compatibility with win_firewall

hubblestack/daemon.py
On startup, by default will retry every 30 seconds forever, unless it's
a single-function run.
After startup, by default will retry every 900 seconds (fifteen minutes)
while continuing to execute the schedule as normal.
=> Fix retry logic for fileserver issues

pkg/windows/build_pkg.ps1, pkg/windows/create_build_env.ps1
Updated the Powershell scripts to make them more robust.
=> Win pkgcreator upgrade

hubblestack/daemon.py, hubblestack/extmods/grains/hostuuid.py
=> Finish fixing the issues from #317 

hubblestack/files/hubblestack_nova/win_secedit.py
Added an if statement that passes through the match variable if its already in SID format on the yaml
=> win_secedit fix for correct match failures

conf/hubble
This is for pull request #309 (module to push hubble config to splunk)
Have added a sample schedule.
=> Sample schedule config for conf_publisher

hubblestack/extmods/modules/pulsar.py, tests/unittests/test_pulsar.py
* this fixes some minor issues with config updating and `recurse: True`
* and adds testing of the above (which found the issues)
=> Fim recurse round #2

hubblestack/extmods/modules/hubble.py, hubblestack/files/hubblestack_nova/command.py, hubblestack/files/hubblestack_nova/cve_scan.py, hubblestack/files/hubblestack_nova/cve_scan_v2.py, hubblestack/files/hubblestack_nova/firewall.py, hubblestack/files/hubblestack_nova/grep.py, hubblestack/files/hubblestack_nova/misc.py, hubblestack/files/hubblestack_nova/mount.py, hubblestack/files/hubblestack_nova/netstat.py, hubblestack/files/hubblestack_nova/openssl.py, hubblestack/files/hubblestack_nova/pkg.py, hubblestack/files/hubblestack_nova/pkgng_audit.py, hubblestack/files/hubblestack_nova/service.py, hubblestack/files/hubblestack_nova/stat_nova.py, hubblestack/files/hubblestack_nova/sysctl.py, hubblestack/files/hubblestack_nova/systemctl.py, hubblestack/files/hubblestack_nova/vulners_scanner.py, hubblestack/files/hubblestack_nova/win_auditpol.py, hubblestack/files/hubblestack_nova/win_firewall.py, hubblestack/files/hubblestack_nova/win_gp.py, hubblestack/files/hubblestack_nova/win_pkg.py, hubblestack/files/hubblestack_nova/win_reg.py, hubblestack/files/hubblestack_nova/win_secedit.py
This is in continuation of pull request  #318 (labelling of tests in profiles (Do not merge) #318)
Made changes in rest of the modules as well incorporating the changes suggested in PR #318
=> feature to run tests based on labels

hubblestack/daemon.py
With this implementation, a large fleet of virtual machines can be grouped in buckets and executed at a different time so that there is no resource crunch on the underlying hardware.
=> Introducing bucketing in hubble

hubblestack/extmods/grains/cloud_details.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
This removed the field from the event dict if it's going to go in the fields dict.
=> Change index extracted fields logic

hubblestack/extmods/modules/pulsar.py, tests/unittests/test_pulsar.py
Attempt to fix #327 (and fix a couple other incidentals would probably show to be broken later)
=> fix pruning to address #327

hubblestack/extmods/modules/win_pulsar.py, hubblestack/extmods/returners/splunk_pulsar_return.py
This speeds up win_pulsar tremendously.  and it also fixes the returner to accept the new inputs from this returner
=> Win pulsar speed fix

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
1) Making http_event_collector_ssl_verify configurable
2) Adding unicode check for custom fields.
=> Making http_event_collector_ssl_verify configurable and unicode check for custom fields

hubblestack/extmods/modules/pulsar.py, hubblestack/extmods/modules/win_pulsar.py, hubblestack/extmods/returners/logstash_pulsar_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
* Actually send `contents` to splunk
* Add periodic refreshes to pulsar.top (both linux and windows)
* Fix an import error in pulsar.py when pyinotify is missing (due to a class inheritance declaration)
=> Pulsar fixes

hubblestack/extmods/fileserver/azurefs.py
see 
https://github.com/hubblestack/hubble/pull/314 
for more context.
There is a problem with the implementation of fallback mechanism for azure containers. It's not working properly with stored access policy. So making some changes to improve it.
=> Bug fix and improvement in azurefs fallback mechanism

pkg/windows/create_build_env.ps1
Faced some problems in creating/automating hubble build for windows. Making changes for the same.
@madchills
Let me know if there there is some better way to handle these.
=> Updating create_build_env.ps1 for creating windows build

pkg/windows/build_pkg.ps1, pkg/windows/hubble-Setup.nsi
This changes the .nsi installer to create a new file user.conf inside /etc/hubble/hubble.d/
I also updated the powershell scripts to work better and more correctly
=> .nsi updates and more!

pkg/windows/pyinstaller-requirements.txt
=> added new requirement for hubble

README.md
Thanks for being in open source, enjoyed the FLOSS Weekly episode...  let me know if I can improve this Pull Request 😃
=> Update README with net-tools install step when running in container

hubblestack/extmods/modules/nebula_osquery.py
Ref https://github.com/hubblestack/hubble/pull/405
=> Format the nebula top data as a list of dicts for consistent order

hubblestack/extmods/returners/graylog_nebula_return.py, hubblestack/extmods/returners/graylog_nova_return.py, hubblestack/extmods/returners/graylog_pulsar_return.py
This is a working version compatible with GELF HTTP Graylog inputs. Tested on Graylog 2.4
=> graylog returner addition

README.md
=> Add note about out of date setuptools

hubblestack/daemon.py
Ref https://github.com/hubblestack/hubble/pull/420
=> Persist transiently-available grains

hubblestack/daemon.py
=> Move daemonization to pre-grains to make service systems happy

hubblestack/extmods/grains/hubbleversion.py, hubblestack/extmods/modules/hubble.py, hubblestack/extmods/modules/nebula_osquery.py, hubblestack/splunklogging.py
- Add hubble version to the grains
- Remove trailing whitespace in nebula_osquery.py
- Fix #448
- Change timestamp in hubble logs to splunk to epoch time
=> Small fixes

conf/hubble, hubblestack/daemon.py, hubblestack/files/hubblestack_nova/misc.py
test from my side. feel free to merge
Changes are self explanatory I hope.
=> Adding min_splay to hubble config

hubblestack/daemon.py
=> Fix --version issues with existing running daemon

hubblestack/extmods/modules/nebula_osquery.py
FDG should replace any needs around `curl`
=> Disable nebula queries with `attach` or `curl`

hubblestack/daemon.py
By moving it into the load_config we can do it before grains generation and speed things up considerably
=> Make --version faster

hubblestack/daemon.py, hubblestack/extmods/fdg/grep.py, hubblestack/extmods/modules/fdg.py, hubblestack/files/hubblestack_nova/grep.py
This PR has the core module for flexible data gathering, as well as the first fdg module (`grep`). Feedback is appreciated! I think the docstring at the top is pretty complete (and is a good primer if you're unfamiliar with the concept).
Obviously there's a lot left to do:
- Tests (I've only done manual tests so far)
- Topfile support
- ~35 million modules (`split`, `osquery`, `stat`, `cat`, `curl`, to name a few)
But it works!
=> Flexible Data Gathering (fdg)

hubblestack/extmods/modules/nebula_osquery.py
* Better documentation
* Some linting
* Better error reporting
@yassingh This shouldn't affect you (as the only real change I made was switching to `mask_with` instead of `mask_by`, but I retained backwards compatibility) but it would be nice if you could review this anyway.
=>  Clean up nebula_osquery masking code

hubblestack/daemon.py
=> Only refresh the pidfile if we're daemonized

hubblestack/daemon.py
this helps to identify and correlate host syslog data with hubble data
=> emit some grains to syslog

hubblestack/files/hubblestack_nova/win_firewall.py
This will stop errors and improve performance
fixes #310
=> fixed trying to load firewall information before it is needed. 

conf/hubble, hubblestack/extmods/fdg/osquery.py, hubblestack/extmods/modules/fdg.py
Topfile support for FDG. Also some other stuff:
* Support for initial chained values in FDG
* Small fixes to conf/hubble that I noticed during testing
=> FDG topfile support

hubblestack/extmods/fdg/curl.py
@fossam You'll have to tell me if this has any gaps around your use case. I left it pretty open (which I think is still ok from a security standpoint since I disabled fdg chaining for this module)
=> FDG Curl module

pkg/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/centos6/pyinstaller-requirements.txt, pkg/centos7/Dockerfile, pkg/centos7/pyinstaller-requirements.txt, pkg/coreos/pyinstaller-requirements.txt, pkg/debian7/pyinstaller-requirements.txt, pkg/debian8/pyinstaller-requirements.txt, pkg/debian9/pyinstaller-requirements.txt, pkg/dev/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/dev/centos6/pyinstaller-requirements.txt, pkg/dev/centos7/pyinstaller-requirements.txt, pkg/dev/coreos/pyinstaller-requirements.txt, pkg/dev/debian7/pyinstaller-requirements.txt, pkg/dev/debian8/pyinstaller-requirements.txt, pkg/dev/debian9/pyinstaller-requirements.txt, pkg/hook-hubblestack.py, pkg/windows/pyinstaller-requirements.txt, pyinstaller-requirements.txt, requirements.txt
=> Add vulners to hook

hubblestack/files/hubblestack_nova/win_secedit.py
=> Fix win_secedit error

doc/contents/auditing_nova.rst
=> add brief note about returners

hubblestack/extmods/fdg/readfile.py
Adds the ability to pull json/yaml data from a file, including the ability to pull data from a subkey of a data structure. Also includes the ability to have nested subkeys with a custom separator. Finally, includes the ability to pull somewhat arbitrary data from "config-style" files.
=> Add FDG module for reading data from files

hubblestack/daemon.py, hubblestack/extmods/modules/hstatus.py, hubblestack/extmods/modules/hubble.py, hubblestack/extmods/modules/nebula_osquery.py, hubblestack/extmods/modules/pulsar.py, hubblestack/status.py
Gather stats. Register signal handler so `kill -10 $hubble_pid` produces a json file of stats (self documented).
=> Sigusr1 status dumpster

utils/hubblestack-cent7dev.dockerfile
https://hub.docker.com/r/hubblestack/cent7dev
=> Add dockerfile for cent7 dev

hubblestack/extmods/modules/nebula_osquery.py
This should drastically reduce the number of entries we need to get most of the secrets masked.
=> Add globbing support to object masking in nebula

tests/unittests/test_readfile.py
Add tests for the rest of the functions in readfile.py
=> Unittests for readfile

hubblestack/extmods/modules/pulsar.py
=> not all pyinotify.WatchManagerError are due to limits

hubblestack/files/hubblestack_nova/vulners_scanner.py
The current version of `vulners_scanner.py` fails silently as it seems that Vulners has updated its API and [no longer returns results wrapped in a `data` object](https://github.com/hubblestack/hubble/compare/develop...brannondorsey:vulners-scanner#diff-34467bb551bbb10b7a509ddbbce6179dL117). The existing behavior will silently fail, reporting a false negative for all scans. In other words, it will report that ALL packages are secure every time (e.g. `'Secure packages': '462 out of 462'`). This PR fixes this bug and now correctly reports the number of vulnerable packages installed on the machine being audited.
Additionally, the existing version of this scanner formats all packages [as if they are `rpm` packages](https://github.com/hubblestack/hubble/compare/develop...brannondorsey:vulners-s …
=> Fix vulners scanner

hubblestack/extmods/fdg/process_status.py, hubblestack/extmods/modules/nebula_osquery.py, tests/unittests/test_process_status.py
My IDE did some auto-formatting for nebula_osquery.py - removing some whitespace or messy indentation, hope that's alright.
=> add process scanning capabilities

hubblestack/status.py
I was unable to import hubble.hec due to the circular import
=> avoid circular import with lazy load

hubblestack/extmods/returners/splunk_generic_return.py
Default would be in the token def (in Splunk).
=> The index was missing from the payload.

hubblestack/daemon.py
Actual question... Pretty sure this should be TERM, not KILL.
=> should be TERM?

hubblestack/extmods/grains/hubbleversion.py, hubblestack/extmods/modules/nebula_osquery.py, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile, pkg/windows/osqueryd_safe_permissions.ps1
Will need to undo the dev dockerfile changes.
=> Merge forward from 3.0 to develop

hubblestack/hec/obj.py
... and from the looks of it, never worked right anyway
=> this broken in PR 565

hubblestack/daemon.py, hubblestack/files/hubblestack_nova/fdg.py
This allows using FDG to create more flexible audit checks.
=> FDG Nova Connector

hubblestack/extmods/modules/conf_publisher.py
Also cleaned up some of the code
=> Remove grains and more secrets from conf_publisher

hubblestack/files/hubblestack_nova/win_secedit.py
Pretty sure all of this should be lowercase.
=> lower case input_string in win_secedit.py

hubblestack/extmods/modules/conf_publisher.py
This makes dealing with this data in splunk easier, as you reference
through a dict with dots.
=> Remove dots by default in conf_publisher

hubblestack/extmods/grains/cloud_details.py, hubblestack/extmods/returners/splunk_nova_return.py
* start with gcp metadata details
* make cloud_details fields configurable so that additional details can be configured from the metadata but only certain ones are reported with returner
=> cloud details changes

hubblestack/extmods/modules/fdg.py
=> Fix typos in fdg module

hubblestack/files/hubblestack_nova/win_auditpol.py, hubblestack/files/hubblestack_nova/win_firewall.py, hubblestack/files/hubblestack_nova/win_gp.py, hubblestack/files/hubblestack_nova/win_pkg.py, hubblestack/files/hubblestack_nova/win_reg.py, hubblestack/files/hubblestack_nova/win_secedit.py
I think I did this right, but it's not tested yet.
=> Add flag in nova profile for domain controller hosts

hubblestack/daemon.py, hubblestack/log.py
This seems to fix most of the memory problems with Hubble.
=> Salt log leak fix

hubblestack/hec/obj.py
This seems to solve the problem of logging queue conditions. It's pretty janky though. For very good reasons, the hubblestack.hec.obj log messages are filtered from splunklogging.
Possible problems with this patch include:
* this doesn't check the status of the hubble logging options (should it??). I was about to add that and thought: these aren't typical log messages. They're events. Queueing to disk should be rare and it doesn't seem to be in the environments where this is needed.
* this doesn't make any attempt to measure remaining queue-space (remaining capacity); should it? Should it report when the queue is full? How would it do this?
=> add logs to queue conditions

hubblestack/hec/obj.py
Move a few logging messages up to ERROR level for production logging.
=> production log bump

hubblestack/extmods/grains/fqdn.py
We shouldn't define the local_fqdn if we don't get a good value
=> Fix local_fqdn grain to remove bad values

hubblestack/extmods/grains/cloud_details.py
I was bored in a meeting and fixed this for you @fossam. It's untested.
=> Only include aws_extra grains if we get a 200 status code

hubblestack/extmods/modules/nebula_osquery.py
As per @fossam recommendation, changing key names used in disk stats to all lowercase.
=> Changing disk stat keys to lowercase

hubblestack/hec/dq.py
… unless we calm this down slightly
=> we never dequeue events that are bigger than the max size

hubblestack/extmods/returners/splunk_fdg_return.py
This should be the last returner that doesn't use the make_hec_args
=> I can't see any reason this isn't right.

hubblestack/extmods/returners/graylog_nebula_return.py, hubblestack/extmods/returners/graylog_nova_return.py, hubblestack/extmods/returners/sumo_nebula_return.py, hubblestack/extmods/returners/sumo_nova_return.py, hubblestack/extmods/returners/sumo_pulsar_return.py
Hello! 
I've tested these Sumologic returners and validated they all work. Also while putting these together, I noticed a bug in the graylog returners (`graylog_nebula_return.py` and `graylog_nova_return.py`) that was created likely with a find/replace that went wrong. 
Thanks!
=> Add Sumologic returners && fixed Graylog returner bug

hubblestack/extmods/fileserver/s3fs.py
Still needs to be tested, but I wanted @jettero's review before he left for the day.
=> Fix s3fs to use cached metadata and files during network outage

hubblestack/extmods/returners/splunk_fdg_return.py
=> missed an import

hubblestack/extmods/modules/win_pulsar.py
Thank you to @SpiritualMadMan for figuring this out in #656!
Fixes #656
=> Fix win_pulsar to correctly use the mask for renames

hubblestack/extmods/fileserver/s3fs.py
Fixed most linting errors except for _Undefined variable '__opts__' /__utils__/___ , the TODO warning and _Catching too general exception_
=> fix linting errors for s3fs.py

hubblestack/extmods/grains/default_gw.py
Still leaves _broad exception_ and _protected-access_ warnings
=> fix linting for default_gw

hubblestack/extmods/fdg/curl.py
Forgot to add the headers to the call.
=> Add headers to fdg curl

hubblestack/extmods/returners/splunk_generic_return.py, hubblestack/utils/stdrec.py
This takes stuff in stdrec.py and breaks it out into more functions. Then it uses one of those new functions for the host value in the payload in splunk_generic_return.py
=> Do error checking on the 'host' value in splunk_generic_return.py

hubblestack/extmods/fdg/curl.py, hubblestack/extmods/fdg/grep.py, hubblestack/extmods/fdg/osquery.py, hubblestack/extmods/fdg/process.py, hubblestack/extmods/fdg/process_status.py, hubblestack/extmods/fdg/readfile.py, hubblestack/extmods/fdg/time_sync.py, tests/unittests/test_process.py, tests/unittests/test_time_sync.py
=> Fix lint fdg

hubblestack/extmods/returners/sumo_nebula_return.py
this sumo returner seems to have broken somewhere along the lines for 3.0.x. This is tested and working now.
=> Fixed bug in sumo_nebula_returner that broke this returner.

hubblestack/extmods/modules/pulsar.py
these are horrific to navigate, and source diving is super hard in here.
let me know if you can think of any way to make these docs more clear. They're pretty confusing even with these "fixes."
=> fixes for pulsar options docs

hubblestack/extmods/grains/cloud_details.py
Bypass proxies when accessing metadata services.
This is not tested!
Let me know if the commit needs to be against 3.0 branch instead.
=> fix for cloud_details grain

hubblestack/extmods/grains/cloud_details.py, hubblestack/extmods/modules/conf_publisher.py, hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_osqueryd_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
I was intending to include this with 3.0.7
=> more 3.0.7 features

hubblestack/daemon.py, hubblestack/hec/obj.py, hubblestack/hec/opt.py
Fixing global __opts__ reference which was missed in PR #706
=> Fixing global opts reference

hubblestack/extmods/returners/sumo_nebula_return.py, hubblestack/extmods/returners/sumo_nova_return.py
I copied what is working for the splunk nebula returner. Not sure how this ever worked for me in the past,  but it did! :shrugs:
=> Fixing again. 

hubblestack/extmods/fdg/ssl_certificate.py
also, some doc strings and log messages now reflect the renamed module
=> bring field names to a better alignment with splunk cim

.pipeline
* rearrange events in the pipline
* make sure the origin/develop branch is checked out
=> try to better guess the required linting

hubblestack/extmods/audit/grep.py, hubblestack/extmods/fdg/osquery.py, hubblestack/extmods/fdg/process.py, hubblestack/extmods/grains/cloud_details.py, hubblestack/extmods/grains/configgrains.py, hubblestack/extmods/grains/custom_grains_pillar.py, hubblestack/extmods/grains/fqdn.py, hubblestack/extmods/grains/osqueryinfo.py, hubblestack/extmods/grains/splunkconfig.py, hubblestack/extmods/modules/audit.py, hubblestack/utils/encoding.py
cloud_details.py, fqdn.py and audit.py are the only files with changes bigger than simple renames, log formatting or added docstring
=> clear linting errors for files in hubblestack/extmods

hubblestack/__init__.py, hubblestack/daemon.py, hubblestack/hec/obj.py, hubblestack/log.py, hubblestack/saltoverrides.py, hubblestack/splunklogging.py, hubblestack/status.py, tests/unittests/test_counters.py
daemon.py, log.py, splunklogging.py, saltoverrides.py, status.py
=> clean linting for .py files in  hubblestack/

hubblestack/hec/opt.py
This file has double commits merged into the same file. Fixing the code.
=> fixing 3.0

.gitignore, hubblestack/extmods/fdg/ssl_certificate.py, hubblestack/hec/dq.py, hubblestack/hec/obj.py, tests/unittests/test_hec_dq.py
Taking the decision to take disk queue improvement in the next release. 
Tweaking log level in fdg ssl_certificate module to control log volume (Log level tweaked from ERROR to DEBUG at one place)
=> Deferring disk queueing improvements for next release.

.gitignore, hubblestack/extmods/fdg/ssl_certificate.py, hubblestack/hec/dq.py, hubblestack/hec/obj.py, tests/unittests/test_hec_dq.py
Reverts hubblestack/hubble#749
=> Revert "Deferring disk queueing improvements for next release."

hubblestack/files/hubblestack_nova/grep.py, requirements.txt, setup.py
Had to resubmit PR https://github.com/hubblestack/hubble/pull/752 due to not being a part of adobe git org.
=> platform.linux_distribution() & platform.dist() replaced with distro.linux_distribution()

hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/utils/s3.py, tests/unittests/test_s3fs_opts.py
The problem here seems to be that I failed to backport a cleanup of this code where the return type of get_s3_key changed. But I did backport a change that relied on that previous cleanup.
=> 3.0.8 s3 fix

hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/utils/s3.py, tests/unittests/test_s3fs_opts.py
=> Fixing s3fs.py from PR#759

.pipeline, hubblestack/hec/dq.py, hubblestack/hec/obj.py, hubblestack/utils/encoding.py, hubblestack/utils/misc.py, tests/unittests/test_hec_dq.py, tests/unittests/test_hec_obj.py
fix the tests and hec.dq so it'll work reliably (hopefully).
I also generated some generic encoder/decoder systems that we'll probably only use in that one place...
=> Fix py3 hec dq

hubblestack/extmods/modules/pulsar.py, tests/unittests/test_pulsar.py
I rebased the fim-single-file fix onto py3. I did have to change a few things to get it to merge cleanly.
=> fim single file [py3 rebase]

hubblestack/extmods/returners/sqlite.py
The logging error was breaking the sqlite returner causing a TypeError, this should fix the issue with the appropriate behaviour.
=> fix error in sqlite returner

contrib/disk-queue-info.py, hubblestack/hec/dq.py
handy in a pinch, normally not needed at all
=> dq view tool

.pipeline, hubblestack/daemon.py, hubblestack/extmods/fileserver/s3fs.py, hubblestack/utils/signing.py, pylintrc, test-requirements.txt, tests/unittests/test_hec_obj.py, tests/unittests/test_process.py
I found a few things we need to fix while trying to build a 4.0 branch
=> various fixes to get py3 branch ready for 4.0 RC1

hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/utils/s3.py
This is PR #783 (s3 rate limit fix) carefully stacked onto 3.0 branch.
=> s3-fix onto 3.0 branch

hubblestack/extmods/fileserver/s3fs.py
* the backport of the new s3 rate limit needed some minor fixes.
=> s3-rate-limit fix backport bugfix

hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/utils/s3.py
This is already in develop, but there were conflicts to resolve merging develop to make 4.0 branch. Until develop *is* the py3/4.0 branch, cherry-pick merges feel like less work.
=> s3-fix merge into 4.0 branch

hubblestack/extmods/fileserver/s3fs.py
this is a backward port of @daveed12 's cache file bugfix
=> backward port of 412bacc

hubblestack/extmods/fileserver/s3fs.py
this is a forward port of the corrupted cache file bugfix
=> forward port 412bacc

hubblestack/utils/signing.py
I fixed the log formatting issues, linting issues, and unnecessary conditions
=> Signing logging

hubblestack/utils/signing.py
These are pretty minor things from (#815) … but the tests don't pass without these fixes.
=> Minor fixes relating to PR815

hubblestack/__init__.py, pkg/windows/dockerfile
- Changing hubble version to 3.0.12
=> Changing hubble version to 3.0.12

pkg/centos6/Dockerfile, pkg/centos6/entrypoint.sh, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian10/entrypoint.sh, pkg/debian8/Dockerfile, pkg/debian8/entrypoint.sh, pkg/debian9/Dockerfile, pkg/debian9/entrypoint.sh, pkg/dev/centos6/Dockerfile, pkg/dev/centos6/entrypoint.sh, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/Dockerfile, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/Dockerfile, pkg/dev/debian9/entrypoint.sh, pkg/hook-hubblestack.py
* various boot script bugs
* various minor package tweaks
=> 4.0 minor fixes

hubblestack/extmods/fileserver/gitfs.py, hubblestack/extmods/utils/gitfs.py, hubblestack/utils/README, hubblestack/utils/signing.py, pkg/centos6/entrypoint.sh
* fix an important bug in pkg/centos6 builds that load the wrong etc/init.d files into the rpm
(this PR assumes #836 is already merged; this PR is also a dup of #837 but pointed at the correct base)
=> 4.0 centos6 fix

hubblestack/extmods/fileserver/gitfs.py, hubblestack/extmods/utils/gitfs.py, hubblestack/utils/README, hubblestack/utils/signing.py
* port gitfs from salt to hubble
* fix an important bug in signing that prevented all signing configs from actually loading
=> 4.0 gitfs port

hubblestack/extmods/utils/s3.py, requirements.txt
access denied, like slowdown, was causing the entire schedule to cease functioning.
These are my proposed fixes, but please consider the implications carefully. I'm not 100% confident this is the right thing to do.
=> S3 access denied

pkg/amazonlinux2016.09/entrypoint.sh, pkg/centos6/entrypoint.sh, pkg/centos7/entrypoint.sh, pkg/centos8/entrypoint.sh, pkg/coreos/entrypoint.sh, pkg/debian10/entrypoint.sh, pkg/debian8/entrypoint.sh, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/centos6/entrypoint.sh, pkg/dev/centos7/entrypoint.sh, pkg/dev/centos8/entrypoint.sh, pkg/dev/coreos/entrypoint.sh, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/entrypoint.sh
some minor changes I rolled into build 78/79, but never PRed (apparently)
=> Other pkg updates

hubblestack/extmods/modules/memleak.py, pkg/hook-hubblestack.py, setup.py
this used to be a lot more difficult to get working. it's a no brainer now because tracemalloc comes with python3
=> resurrect old memory leak hunter

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
I officially have no idea why I changed the checkout from a naked checkout. I tested a bunch of things that might have caused me to change it and none of them are valid.
This reverts the checkout to the original method.
(Side note: I also opened this against develop... #849)
=> 4.0 revert checkout

hubblestack/extmods/modules/nebula_osquery.py, hubblestack/extmods/returners/splunk_osqueryd_return.py
attempt to forward port #803 and #804
=> Some final forwardports

.gitignore, pkg/amazonlinux2016.09/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/debian10/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
=> freeze ffi version to avoid requiring ruby 2.3

hubblestack/extmods/modules/nebula_osquery.py
10000 second timeout is incredibly large and distruptive both for
data and schedule execution.
=> command timeout fix for 4.0 branch

pkg/centos8/Dockerfile, pkg/dev/centos8/Dockerfile
I think we had an old stale layer above and the dnf -y update
(which seems duplicate) can fix the issue. At the same time,
combine up a couple run lines.
=> dnf was getting 404 and bad mirror results

pkg/amazonlinux2016.09/entrypoint.sh, pkg/debian10/entrypoint.sh, pkg/debian8/entrypoint.sh, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/entrypoint.sh
The builds are all working, but literally half never make it to artifactory from jenkins due to subtle naming issues.
It seems like we should probably be building packages and naming artifacts in pipeline groovy to avoid these things.
=> these files never get pushed to artifactory because of subtle naming issues

pkg/amazonlinux2016.09/entrypoint.sh, pkg/debian10/entrypoint.sh, pkg/debian8/entrypoint.sh, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/entrypoint.sh
=> fpm puts out name_ver-iter_arch; artifactory wants name-ver-iter.arch; k

hubblestack/extmods/returners/sqlite.py
some minor tweaks to this reterner. nobody's really using this returner yet, but it's causing coverage warnings in the unit tests.
=> some minor changes to sqlite returner

hubblestack/utils/platform.py, hubblestack/utils/zfs.py, tests/unittests/utils/test__compat.py, tests/unittests/utils/test_dictupdate.py, tests/unittests/utils/test_network.py, tests/unittests/utils/test_win_functions.py, tests/unittests/utils/test_win_osinfo.py, tests/unittests/utils/test_win_reg.py, tests/unittests/utils/test_yamlloader.py, tests/unittests/utils/test_zfs.py
- Moved test cases for:
- salt.utils.win_functions
- salt.utils.network
- salt._compat
- salt.utils.win_osinfo
- salt.utils.win_reg
- salt.utils.dictupdate
- salt.utils.zfs
- salt.utils.yaml/salt.utils.yamlloader
=> Final set of test cases for Grains dependencies

.pipeline, pkg/abandoned/debian7/pyinstaller-requirements.txt, pkg/dev/abandoned/debian7/pyinstaller-requirements.txt, pkg/generate-requirements.sh, pkg/hook-hubblestack.py, pkg/scripts/pyinstaller-requirements-debian7.txt, requirements.txt, test-requirements.txt, tests/unittests/conftest.py, tests/unittests/hubble.config, tests/unittests/test_loader.py
this might just fix the various test problems installing old pprint packages and salt 3000 builds and things.
=> use the modern requirements rather than that old test-req file

.pipeline
Basically none of our PRs can pass linting at this time, so I'm just going to defang it until we can make a commitment to get everything linted.
=> defang pylint in 4.1 branch

.pipeline
Basically none of our PRs can pass linting at this time, so I'm just going to defang it until we can make a commitment to get everything linted.
=> defang pylint  in develop branch

hubblestack/daemon.py, hubblestack/log.py, hubblestack/splunklogging.py, hubblestack/utils/stdrec.py
This is the same change as #914 and #915. This is the backport to 4.0.
=> Update splunklogging SplunkHandler class with new grains on refresh

hubblestack/modules/iptables.py, hubblestack/modules/mount.py, hubblestack/utils/args.py, hubblestack/utils/context.py, hubblestack/utils/mount.py, hubblestack/utils/yaml.py, hubblestack/utils/yamldumper.py, tests/support/mixins.py, tests/unittests/modules/test_iptables.py, tests/unittests/modules/test_mount.py
- Moved salt.modules.iptables to hubblestack.modules.iptables
- Moved salt.modules.mount to hubblestack.modules.mount
- Moved salt.utils.context to hubblestack.utils.context
- Moved salt.utils.mount to hubblestack.utils.mount
- Moved salt.utils.yamldumper to hubblestack.utils.yamldumper
- Added corresponding unit tests and updated mixins.py to load \_\_mods\_\_ in unit tests
=> Added yamldumper, context, iptables and mount

hubblestack/__init__.py, pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile, pkg/osquery/Dockerfile, pkg/windows/dockerfile
testing out the new build process as much as anything else.
=> version up from 4.0.0

pkg/coreos/entrypoint.sh
Moving service file for coreos and placing it into /etc/hubble/hubble-example.service
=> Updating entrypoint.sh

hubblestack/utils/signing.py
Added profile signing feature we've been working on in our peer programming sessions. Tested and validated changes with @mew1033.
=> Added profile certificate feature

tests/unittests/modules/test_curl.py
Adding test cases for curl module
=> Adding test cases for curl module

hubblestack/__init__.py, pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
=> Version up 4.0.1

hubblestack/extmods/comparators/boolean.py, hubblestack/extmods/comparators/certificate.py, hubblestack/extmods/comparators/dict.py, hubblestack/extmods/comparators/file_permission.py, hubblestack/extmods/comparators/list.py, hubblestack/extmods/comparators/number.py, hubblestack/extmods/comparators/string.py, hubblestack/extmods/comparators/version.py, hubblestack/extmods/hubble_mods/bexpr.py, hubblestack/extmods/hubble_mods/command_line_parser.py, hubblestack/extmods/hubble_mods/curl.py, hubblestack/extmods/hubble_mods/fdg.py, hubblestack/extmods/hubble_mods/grep.py, hubblestack/extmods/hubble_mods/misc.py, hubblestack/extmods/hubble_mods/osquery.py, hubblestack/extmods/hubble_mods/pkg.py, hubblestack/extmods/hubble_mods/readfile.py, hubblestack/extmods/hubble_mods/service.py, hubblestack/extmods/hubble_mods/ssl_certificate.py, hubblestack/extmods/hubble_mods/stat.py, hubblestack/extmods/hubble_mods/sysctl.py, hubblestack/extmods/hubble_mods/time_sync.py, hubblestack/extmods/hubble_mods/util.py, hubblestack/extmods/hubble_mods/win_auditpol.py, hubblestack/extmods/hubble_mods/win_firewall.py, hubblestack/extmods/hubble_mods/win_pkg.py, hubblestack/extmods/hubble_mods/win_reg.py, hubblestack/extmods/hubble_mods/win_secedit.py
Adding detailed documentation for modules and their sample output.
=> Documentation for Audit Modules (Nova-rewrite)

README.rst, hubblestack/audit/command_line_parser.py, hubblestack/audit/curl.py, hubblestack/audit/fdg.py, hubblestack/audit/grep.py, hubblestack/audit/misc.py, hubblestack/audit/osquery.py, hubblestack/audit/readfile.py, hubblestack/audit/ssl_certificate.py, hubblestack/audit/time_sync.py, hubblestack/audit/util.py, hubblestack/audit/win_reg.py, hubblestack/audit/win_secedit.py, hubblestack/comparators/dict.py, hubblestack/comparators/list.py, hubblestack/module_runner/audit_runner.py, hubblestack/module_runner/runner.py, hubblestack/modules/audit.py, hubblestack/modules/fdg.py, hubblestack/returners/splunk_fdg_return.py, tests/unittests/modules/test_readfile_new.py, tests/unittests/modules/test_ssl_certificate_new.py, tests/unittests/modules/test_win_secedit.py
These are several bug fixes in the audit re-write.
=> Hubble Audit re-write Bug fixes

hubblestack/modules/network.py, hubblestack/utils/decorators/path.py, hubblestack/utils/network.py, hubblestack/utils/validate/net.py, tests/unittests/modules/test_network.py
- Added hubblestack/modules/network.py
- Added hubblestack/utils/validate/net.py
- Added hubblestack/tests/unittests/modules/test_network.py
=> Added network module

.pipeline, hubblestack/extmods/grains/cloud_details.py
=> GCP iterator bug

hubblestack/extmods/modules/signing.py, hubblestack/utils/signing.py
backport intermediate signing cert fix
=> Intermediate signing fix

pkg/dev/centos6/Dockerfile
(plus, copy #982 fix back to dev/ for centos6)
=> pip 20.2 fix for coreos

pkg/coreos/entrypoint.sh
I thought I already merged this patch, but I missed it somehow.
=> somehow I missed the actual fix needed in the last merge

hubblestack/returners/sqlite.py
Sqlite returner wasn't working. Fixing that.
=> fixing sqlite returner

pkg/amazonlinux2016.09/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile
=> dang. the worst typo possible

hubblestack/audit/pkg.py, hubblestack/audit/service.py, hubblestack/audit/ssl_certificate.py, hubblestack/audit/sysctl.py, hubblestack/audit/time_sync.py, hubblestack/comparators/dict.py, hubblestack/module_runner/runner_utils.py
A few audit modules did not support chaining. Fixed them.
=> Fixing chaining issues

hubblestack/audit/misc.py
Adding missing Misc module method: test_mount_attrs()
=> Adding missing Misc module method

pkg/dev/centos8/Dockerfile, pkg/dev/debian8/Dockerfile
Python and fpm changes for Debian-8 and Centos-8
=> Python and fpm changes for Debian-8 and Centos-8

hubblestack/audit/win_pkg.py
Negative test case wasn't correctly written
=> win pkg audit result/audit_value bugfix

pkg/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile
This should be the last of it. I mean to cut and paste the ruby and local fixes from centos7, but amazon linux wants to be a little different, so I had to get to ruby23 in a different way.
=> amazon linux build fixes

hubblestack/audit/grep.py, hubblestack/audit/misc.py, hubblestack/audit/stat.py, hubblestack/comparators/dict.py, hubblestack/comparators/list.py, hubblestack/module_runner/runner_utils.py, tests/unittests/modules/test_grep.py, tests/unittests/modules/test_stat.py
- Check for directory in grep and stat modules
- Misc module fix
- Adding ignore_case in list and dict comparator
=> Grep/Stat Module bug fixes

hubblestack/comparators/file_permission.py, hubblestack/fileserver/azurefs.py, hubblestack/module_runner/comparator.py, hubblestack/module_runner/runner.py, hubblestack/modules/audit.py
- For auth exception, it was going in infinite loop.
- Reduce logging for azure lib.
- audit.run verbose=None was treated as True
- check for 'type' in comparator, correcting error msg
- boolean check in file_permission comparator
- Checking for 'args' in audit run
=> Various Bug fixes

hubblestack/returners/splunk_fdg_return.py
Linux and windows have different slashes in file paths. Fixing it for windows.
=> fixing fdg sourcetype for windows

hubblestack/audit/grep.py
=> Grep fix for chaining

hubblestack/audit/grep.py, hubblestack/audit/stat.py
- For stat, if dictionary came in chaining. We were not taking it
- For grep chaining, we only expected content. Fix is to support file from chaining as well.
=> Grep and stat fixes

hubblestack/audit/fdg.py
With the current code, even if error was present, the fdg module resulted in **Success**. Fixed that.
=> fdg module should return negative with error case

hubblestack/modules/audit.py, pkg/windows/entrypoint.ps1
1. If the value of verbose was of boolean type, it went in else block, overwriting the value to **None**. Fixed that.
2. Fixed buildinfo in windows package
=> Beta Build bugs

pkg/windows/entrypoint.ps1
Buildinfo string needs to be replaced before pyinstaller runs
=> Buildinfo string needs to be replaced before pyinstaller runs

pkg/amazonlinux2016.09/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh
=> minor bug regarding init.d file

pkg/windows/hubble_config_permissions.ps1
hubble config permissions file was incorrectly written, corrected that
=> correcting hubble config permission script

hubblestack/audit/bexpr.py, hubblestack/module_runner/audit_runner.py, tests/unittests/modules/test_bexpr.py
Recently the check_id was renamed to check_unique_id, and that was being referred in bexpr module. Changed it here also.
=> check_id is renamed to check_unique_id

requirements.txt, setup.py
The new version of urllib3 seems to have a bug. Pinning to an older tested version.
=> pinning urllib3 version

pkg/windows/entrypoint.ps1
The sha file format needs to be txt file.
=> correcting sha file format

pkg/windows/entrypoint.ps1
Missed changing the sha file name at the second place in previous commit. Needs to be changed here as well
=> sha file name is changed

hubblestack/hec/obj.py
There seems to be some confusion about the proxy settings and I'm not sure how to fix the docs or indeed, if there are any docs.
A top level config item of `https_proxy` will be used by the hec obj unless there's a `proxy` setting in the hec options for an individual hec endpoint; in which case, that will be used instead.
The https/http protocol of the proxy was made to follow the `http_event_server_ssl` setting for the endpoint no matter what was in the proxy setting. This patch allows for the use of http proxies with https endpoints... which is a thing that should hopefully only come up in testing? probably? It certainly did for me.
I found that some https things would definitely work with squid3, but only if it was in certificateles https mode; which the PoolManager and/or splunk do …
=> allow for http://proxy:servers with https hec endpoints

conf/hubble-d-conf
Just a slight tweak to this example file.
=> add more example, rephrase comments

pkg/README.md
=> modified README in pkg folder

pkg/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile
=> sqlite-devel missing in AL

hubblestack/grains/cloud_details.py, hubblestack/utils/signing.py
- nothing in here is critical... they're just errors
- don't pass after you do something. that's just silly
- missed one
- we have an error below these. these are only informational
- fix cloud_details logic and prevent KeyError exception
=> goofy log msgs

hubblestack/grains/cloud_details.py, hubblestack/utils/signing.py
bring PR1084 forward to master
=> merge forward to master

hubblestack/files/hubblestack_nova/oval_scanner.py, hubblestack/modules/hubble.py, hubblestack/returners/splunk_nova_return.py, requirements.txt
`oval_scanner.py` has been refactored to capture greater details about advisories, and `splunk_nova_return.py` has been refactored to send those details to a Splunk backend.  For comparison, this is how data in Splunk looks before the refactor:
```
{ 
check_id: RHSA-2015:1705: bind security update (Important)
check_result: Failure
description: Vulnerable Package(s): bind-libs-32:9.11.4-9.P2.el7, bind-libs-lite-32:9.11.4-9.P2.el7, bind-license-32:9.11.4-9.P2.el7, bind-utils-32:9.11.4-9.P2.el7
dest_fqdn: <hostname>
dest_host: <hostname>
dest_ip: <ip address>
job_id: <job_id>
minion_id: <minion id>
system_uuid: <system uuid>
}
```
After the refactor, the data looks like this:
```
{ 
advisory: { 
RHSA-2020:2344: https://access.redhat.com/errata/RHSA-2020:2344
}
check_id: RHSA-2020:2344: bind …
```
=> oval_scanner.py and splunk_nova_return.py enhancements/fixes

hubblestack/fileclient.py, hubblestack/files/hubblestack_nova/oval_scanner.py, hubblestack/files/hubblestack_nova/stat_nova.py, hubblestack/modules/hubble.py, hubblestack/returners/splunk_nova_return.py, requirements.txt
* Windows file cache bug
* Stat_nova mode value fix.
* Oval Scanner changes
=> adding latest code from develop

hubblestack/version.py
=> Updating hubble version

.github/workflows/pre-commit.yaml, .github/workflows/pytest.yaml, .pre-commit-config.yaml, hubblestack/audit/misc.py, hubblestack/audit/win_reg.py, tests/unittests/grains/test_core.py
but we can resurrect all that functionality with github actions
=> we retired the open source jenkins

pkg/windows/python_build/build_python.ps1
Create directory only  if directory does not exists
=> Build python script changes, Create directory only  if directory does not exists

hubblestack/daemon.py
Fix when OS is windows and only environment needs to be set
=> FIPS: Fix when OS is windows and only environment needs to be set

hubblestack/modules/yumpkg.py
Adding rocky linux 8 as part of yum pkgs to enable pkg module to be run on rocky linux 8
=> adding rocky to yum pkgs

pkg/flatcar.arm64/Dockerfile, pkg/flatcar.arm64/entrypoint.sh
Support for Flatcar ARM64
Required moving a couple of symbolic links around for osquery, but otherwise tracks with the coreos build
=> Flatcar support

pkg/flatcar.arm64/entrypoint.sh
This aligned better with previous builds.
=> Last path fix for flatcar

hubblestack/audit/misc.py, hubblestack/files/hubblestack_nova/misc.py, hubblestack/grains/core.py, requirements.txt
removed shell=True and python_shell=True statements from code / refactored bash code to native python
=> Shell true

hubblestack/grains/core.py
We add a simple check to see whether there is a `features` line
=> Systemctl might not output the expected info
