hubblestack/hubble

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
On hosts with a misconfigured (or not configured) fqdn, the fqdn_ip4 grain can end up with a useless value in it. Let's not settle for that value.
=> Never settle for 127.x.x.x ip address if you can help it (splunk returners)

hubblestack/extmods/modules/nebula_osquery.py, pkg/windows/build_pkg.ps1, pkg/windows/create_build_env.ps1, pkg/windows/hubble-Setup.nsi
This change satisfies the git requirement on computers that don't have git already installed.  It uses PortableGit and runs from the git-cmd.exe instead of the regular command prompt.
I also changed the logic to allow windows server 2008 to use osquery.  Osquery updated their software  to work with 2008 a few months ago, so now we can allow osquery to work in hubble for those machines.
=> 'windows fixes'

hubblestack/extmods/grains/osqueryinfo.py
The aim of this commit is to make dealing with missing binaries easier and to avoid unexpected failures.
TODO: log in case the binary wasn't found.
=> additional grains osqueryversion and osquerybinpath

hubblestack/extmods/returners/logstash_nebula_return.py, hubblestack/extmods/returners/logstash_nova_return.py, hubblestack/extmods/returners/logstash_pulsar_return.py
These three returners are initial working concepts for ingesting Hubble data into Logstash for use in ELK stacks. The http input module for Logstash is required, as well as enabling the json filter source:
Example logstash config:
```
input {
http {
port => '8080'
host => '0.0.0.0'
type => 'hubble'
user => 'hubble'
password => 'password'
}
}
filter {
json {
source => 'message'
}
}
output {
elasticsearch { hosts => ["localhost:9200"] }
stdout { codec => rubydebug }
}
```
=> initial working Logstash HTTP input returners

pkg/windows/create_build_env.ps1, pkg/windows/hubble-Setup.nsi
These few simple changes make it possible to get a working environment with the powershell script, and allow for correct upgrading.
=> Win upgrade uninstall fix

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile
Augeas lenses default now in /opt/osquery/lenses, 
also systemd service file removed for centos6.
=> augeas in all dockerfules & centos 6 systemd removal

hubblestack/extmods/modules/hubble.py
This will vastly improve the performance of hubble.top, especially with slow backends like gitfs with gitpython.
=> Fix double-sync for hubble.top

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile
These commits aim to bring osquery 2.7.0 to Hubble packages. Only the build process has been tested.
When using these changes to build packages note:
0. `docker pull <distro_image>` before the build to have the latest as a starting point
1. Hubble develop branch is used for checkout in the Dockerfiles (v2.2.3 -> develop)
2. Hubble version was left 2.2.3 for package names.
=> update all Dockerfiles for osquery 2.7.0 build

hubblestack/files/hubblestack_nova/mount.py, hubblestack/files/hubblestack_nova/systemctl.py
Ref https://github.com/hubblestack/hubble/pull/192
@anuragpaliwal80 I fixed up the trailing whitespace and tabs mixed with spaces. We also noticed that your old version had a command injection vulnerability -- if you passed in a semicolon as part of the service name you could inject a command into your `cmd.run`. That's pretty easily fixable -- I could have just used `cmd.retcode` instead to get the results you wanted. However, I also happened to know that salt has a module which can tell us whether a service is enabled. So I simplified your module to use that function. Keep me posted if you have any questions/concerns.
Edit: also removed trailing whitespace from mount.py
=> Fix up systemctl.py

hubblestack/extmods/modules/pulsar.py, hubblestack/extmods/modules/win_pulsar.py
@rashmip29 FYI. Looks like we never tested for multiple items under a list heading in the topfile, so it never had to recurse deep.
=> Fix pulsar.top

hubblestack/files/hubblestack_nova/misc.py
@anuragpaliwal80 Can you share these changes with your team, and also review them for me? I did not test them but I'm pretty sure I kept the logic correct.
`python_shell=True` should be used as a last resort, and never with a command which has user arguments in it, or else you risk command injection. In many places, you were using `python_shell=True` just so you could do `; echo $?`. This is unnecessary, as salt has `cmd.retcode` which just returns the retcode. Similarly, you have other places where you pipe output to /dev/null -- this is also unnecessary, as you have all of these options in salt:
- `cmd.run_all` (which gives you a dictionary with stdout, stderr, retcode, etc)
- `cmd.run` (combines stdout and stderr into a single string)
- `cmd.run_stdout` (only returns stdout)
- …
=> Fix command injection vulnerabilities in misc.py

hubblestack/extmods/fileserver/azurefs.py
This was causing azurefs hosts to only take the first version of a file unless the cache is cleared manually.
=> Add hash cache invalidation to azurefs

hubblestack/extmods/fileserver/azurefs.py
Closes https://github.com/hubblestack/hubble/issues/248
=> Fix errors for azurefs when hash_cachedir doesn't exist

hubblestack/extmods/grains/fqdn.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
Apparently `socket.getfqdn()` has some reliance on DNS being configured correctly. We ran into this on a host whose reverse IP lookup was resolving to both the host, and the host's load balancer. This resulted in inconsistent results from `socket.getfqdn()`, but it appears that `hostname --fqdn` is consistent even under these circumstances.
So I added a new custom grain, `local_fqdn`, using `hostname --fqdn`.
@madchills Because I don't know the workings of the `hostname` command on Windows, I have it defaulting to `socket.fqdn()`. At some point we should add windows-specific code here to try to avoid similar issues on Windows.
=> Add local_fqdn grain and add dest_fqdn to splunk events

README.md
On a bare bones install of CentOS, the setuptools package is not
installed. I've updated the documentation to include installing the
dependant package.
=> [DOC] Added dependency to documentation

hubblestack/daemon.py, hubblestack/extmods/grains/hostuuid.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
This deserves a fair amount of review. @fossam to make sure this hits all his bullet points WRT unique IDs for sessions and hosts. @madchills for any problems you see regarding the python.
Defaulting to hourly grains refreshes, and sending those to splunk as well if configured with splunk_logging
@mew1033 and @fossam is there a good way to get the data structure to nest in the splunk event? Right now the grains are just hitting splunk as a giant string:
https://www.dropbox.com/s/1fcpct1la3xaye6/Screenshot%202017-12-14%2011.43.17.png?dl=0
I would love to get them as a nice nested thing so you can query the fields. I tried just sticking the dictionary in the message field as an actual dictionary, but the event never made it to splunk. Do I need to shove them in as top-level fields?
Also …
=> Add periodic grains refresh and session/host UUIDs

hubblestack/files/hubblestack_nova/win_firewall.py
I get an error on this mod, despite not running it on windows. It was driving me nuts.
```[ERROR   ] Failed to import nova /win_firewall.py, this is due most likely to a syntax error:
Traceback (most recent call last):
File "/usr/local/python/python2.7/lib/python2.7/site-packages/hubblestack-2.2.11-py2.7.egg/hubblestack/extmods/module
s/nova_loader.py", line 1930, in _load_module
), fn_, fpath, desc)
File "/var/cache/hubble/files/base/hubblestack_nova/win_firewall.py", line 197
return False
^
IndentationError: unindent does not match any outer indentation level
```
=> bad indent level

hubblestack/extmods/modules/pulsar.py
This should fix the edge case where the exclusion IS a dictionary, but IS NOT regex.
=> Fix pulsar exclusion logic

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
We're getting lots of events where Hubble thinks the hostname is "localhost.localdomain." I posted about the problem here https://stackoverflow.com/questions/48230377/why-does-pythons-socket-getfqdn-return-localhost-localdomain-sometimes
This should at least prevent the weird hostnames from appearing. Better to have the IP address than just "localhost."
I don't have any hosts that are having this problem, so I wasn't able to test this change.
=> Avoid setting fqdn to localhost at all costs

pkg/centos7/hubble.service, setup.py
Not sure if this is the best approach, but as it stands the binary the current hubble.service file is looking for (via /opt/hubble/hubble) doesn't exist.  It was suggested to use a symlink in a prior PR, but the binary itself is non-existent in this case. ,
=> Systemd service issue

hubblestack/daemon.py
If there's a pidfile, check to see if it's hubble. If it is, kill the other one or die.
My thinking is that if we `hubble -d` we wish to start or restart. Writing and checking pidfiles does us no good at all if we're in systemd's simple process tracking mode though — in which mode, hubble would be started without the '-d' and would never attempt to daemonize.
=> pidfile issues (check_pidfile() to see if Hubble is already running)

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
This PR doesn't alter logic in any way. Because we're assigning to `hec` without using a `global` keyword, we're creating a local variable that shadows the global anyway. But since we're not using the global, we should still get rid of it since it's misleading.
=> Remove global `hec` and some unused code

hubblestack/files/hubblestack_nova/misc.py
@anuragpaliwal80 @yassingh If you need these checks, we need to figure out how to do them more responsibly, or we need to figure out how to only enable them on DME hosts. Executing a `find` across the whole disk once is irresponsible -- it will peg the CPU for a long time, especially on big disks. But doing it 6 times is unacceptable.
My preference would be to remove these functions altogether, but for now I just make them fail fast.
=> Disable all `find` commands that traverse the whole disk

hubblestack/extmods/fileserver/azurefs.py, pkg/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/amazonlinux2017.03/pyinstaller-requirements.txt, pkg/centos6/pyinstaller-requirements.txt, pkg/centos7/pyinstaller-requirements.txt, pkg/coreos/pyinstaller-requirements.txt, pkg/debian7/pyinstaller-requirements.txt, pkg/debian8/pyinstaller-requirements.txt, pkg/debian9/pyinstaller-requirements.txt, pkg/dev/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/dev/amazonlinux2017.03/pyinstaller-requirements.txt, pkg/dev/centos6/pyinstaller-requirements.txt, pkg/dev/centos7/pyinstaller-requirements.txt, pkg/dev/coreos/pyinstaller-requirements.txt, pkg/dev/debian7/pyinstaller-requirements.txt, pkg/dev/debian8/pyinstaller-requirements.txt, pkg/dev/debian9/pyinstaller-requirements.txt
Azure split out their libraries in the latest version, so we had a few small changes required to get azurefs working again.
=> Fixes for azure sdk updates

hubblestack/daemon.py, hubblestack/extmods/modules/win_pulsar_winaudit.py
We are facing memory problem on windows machines. If a large number of file operations are going on the system, hubble's memory increases to more than 1GB. So this PR contains following changes:
1. Avoiding to print a large object ( more explanation in daemon.py )
2. Hash is calculated for all the objects returned by _pull_events() irrespective of where the object is to be monitored or not. This has been handled in this PR ( more explanation in win_pulsar_winaudit.py )
3. It seems that win_pulsar.py was replaced with a very old version in the commit https://github.com/hubblestack/hubble/commit/7cccf7b9e92dfbc32c0253bc3d63418962852dcd
. So I have tried to put back the changes which were lost in that commit. 
Please don't merge this PR today. We are waiting for tomorrow to verify the …
=> Making changes to improve windows pulsar performance

hubblestack/daemon.py
Turns out salt is already using [RotatingFileHandler](https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler) so this should keep our total log space under 200MB by default. It is also user configurable.
=> Automatically rotate our own logfiles

hubblestack/extmods/grains/cloud_details.py, hubblestack/extmods/returners/logstash_nebula_return.py, hubblestack/extmods/returners/logstash_nova_return.py, hubblestack/extmods/returners/logstash_pulsar_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
NOTE: This will change the values that go into Splunk. Instead of cloud specific data, we'll get normalized (where possible) data. 
aws_instance_id --> cloud_instance_id
aws_account_id --> cloud_account_id
azure_vmId --> cloud_instance_id
azure_subscription_id --> cloud_account_id
etc.
=> Move cloud_details to a grain and normalize names

hubblestack/daemon.py
Added an optional parameter -j for printing the output of single run function in json format. If this parameter is not given when running any function, existing functionality works.
Example command:
hubble hubble.audit -vv -j
=> argument to print output of single function run in json format

hubblestack/extmods/modules/pulsar.py
On Debain 7:
root@eqx-temp7:/var/log# cat hubble
2018-03-06 22:02:14 [hubblestack.daemon][INFO ] Setting up the fileclient/fileserver
2018-03-06 22:02:24 [hubblestack.daemon][INFO ] Starting main loop
2018-03-06 22:02:30 [hubblestack.daemon][ERROR ] Error executing schedule
Traceback (most recent call last):
File "hubblestack/daemon.py", line 95, in main
File "hubblestack/daemon.py", line 210, in schedule
File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/pulsar.py", line 274, in process
sub['stats'] = salt'file.stats'
File "/opt/hubble/hubble-libs/salt/modules/file.py", line 3375, in stats
raise CommandExecutionError('Path not found: {0}'.format(path))
CommandExecutionError: Path not found: /etc/hubble/fim_canary.tmp
=> Fixing exception on Debain 7

pkg/hook-hubblestack.py
Hubble is not able to load azurefs modules because of the changes in its dependencies. This should fix it.
=> Adding azure dependencies in hook file

hubblestack/daemon.py, hubblestack/extmods/fileserver/azurefs.py
If an azurefs container is not accessible for hubble host, it's cache folder is deleted so that the stale files are not served from that container anymore.
NOTE: In case all the containers are inaccessible, cache folder will deleted for all containers. But in this case, the code will not reach the part where 'hashes' directory is deleted. As a result, hubble will keep serving the file from the last azurefs state if all the containers are inaccessible.
=> Clear cache of azurefs containers which are not accessible anymore

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2017.03/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2017.03/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
This does a few things:
* Automatic checksums for packages
* --iteration support
* Remove /etc/hubble/hubble from list of config files in FPM (so we can push new scheduled jobr with new versions)
We still need to update the osquery-building code.
=> Dockerfile updates

hubblestack/extmods/modules/pulsar.py
Includes a maximum file size (defaults to 20KB). Also adds a max file
size for checksums (defaults to 100MB). Adds the size from
os.path.getsize if `stat` is set.
=> Add ability to fetch contents of changed files

hubblestack/files/hubblestack_nova/misc.py
Added function which does the following:
Checks if value of PASS_MAX_DAYS is less than or equal to 90 (passed via profile args)
For each user (other than except_for_users), checks if maximum days for password expiry is less than 90
Sample profile data:
```
ensure_max_password_expiration:
data:
CentOS Linux-7:
tag: CIS-5.4.1.1
function: ensure_max_password_expiration
args: 
- 90
- usr1, usr2
description: Ensure max password expiration days is set correctly for each user
```
=> misc function for passwd expiry days check

hubblestack/splunklogging.py
… but continue to allow maintainers to add index time fields from hubble config.
(I had accidentally pushed this branch to the hubblestack repo, rather than my own repo... when I deleted the branch, it killed PR #293 — so I just submitted a new one.)
=> nix the defaults

conf/hubble, hubblestack/daemon.py, hubblestack/extmods/grains/systemuuid.py, hubblestack/extmods/modules/nebula_osquery.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
* Fix systemuuid grain for missing osquery
* Don't assume we have system_uuid in grains for splunk returner
* Log splunk options at debug level to better protect token
* Move splunk_index_extracted_fields to the top level of the config
* Fix osquery timing for better formatting for splunk
* Fix negative times in osquery timing
=> Another fix dump

conf/hubble, hubblestack/extmods/grains/custom_grains_pillar.py
Needs to add the following sort of section in config file:
```
##############################################
##############################################
custom_grains_pillar:
grains:
- selinux: selinux:enabled
- release: osrelease
pillar:
- ntpserver: network_services:ntpserver
```
To add any of these fields with each log, user can use custom_fields option, for ex to add release and ntpserver with each log:
```
hubblestack:
returner:
splunk:
- token: <token>
indexer: <indexer>
index: hubble
sourcetype_nova: hubble_audit
sourcetype_nebula: hubble_osquery
sourcetype_pulsar: hubble_fim
sourcetype_log: hubble_log
custom_fields:
- release
- ntpserver
splunklogging: True
```
=> Adding option to fetch custom grains and pillar

conf/hubble, hubblestack/daemon.py, hubblestack/extmods/grains/configgrains.py, hubblestack/extmods/modules/nebula_osquery.py, hubblestack/splunklogging.py
=> Fix configgrains to separate from hubblestack returner config

hubblestack/extmods/modules/hubble.py
when no profile (config) was being passed to hubble.audit, labels were not being honoured as they needed to passed to top function in hubble.py
=> fix for executing labelled tests when hubble.audit with no configs is run

hubblestack/daemon.py, hubblestack/extmods/modules/pulsar.py
This option also disables the pidfile for the new proc.
This is obviously false by default, but for testing I want the ability to run more than one process.
=> Add option to ignore running hubble proc

hubblestack/daemon.py
Found this in testing. Still results in exit, but with a stacktrace that's not pretty.
=> Fix two exit() issues

hubblestack/daemon.py, hubblestack/extmods/grains/fqdn.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
* Adds `grains_persist` config for list of grains to persist across
refreshes
* Adds 'local_ip4' grain that best-guesses the ip address of the default
gateway interface
* Adds error filtering to local_fqdn grain
=> Add a few fqdn/ip-related grains changes

hubblestack/extmods/grains/splunkconfig.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py
Also set up the splunk returners to use this config over __opts__ if it
is present. This allows for splunk config to be updated without a hubble
restart. Note that these changes should have no effect on
splunklogging.py because config is only processed on startup, but I made
the changes anyway for consistency (for when we DRY later)
=> Add grain to read splunk config from hubble.d/*.conf

hubblestack/extmods/modules/pulsar.py
The setting logs seem to go to splunk, should the error?
=> add proper error handling for cases where we can't write to /proc/sys

pkg/windows/hubble-Setup.nsi
added logic to not create the User.conf if they don't enter Splunk Token information on the Hubble config page (or add flags on silent install)
=> Windows Hubble-Setup.nsi skip user.conf creation

hubblestack/daemon.py, pkg/dev/centos7/Dockerfile
With these changes, we can add build info to a hubble build. We simply need to place file named "hubble_buildinfo " in the directory which is to be mounted as "/data"
The file should contain ```__buildinfo__``` object in standard python format. For example:
```
[root@ip-10-36-1-20 tmp]# cat hubble_buildinfo 
__buildinfo__ = { 'version' : '1.1.26',
'creator' : 'yash',
'date' : '06.04.2018',
'branch' : 'develop',
'flavor' : 'dme' }
```
If this file is found in /data , it's contents are appended to ```hubblestack/__init__.py``` file. The resultant file looks something like this:
```
[root@ip-10-36-1-20 centos7]# cat /opt/hubble/hubble-libs/hubblestack/__init__.py 
__version__ = "2.3.4-2-8-g6e5c919"
__buildinfo__ = { 'version' : '1.1.26',
'creator' : 'yash',
'date' : '06.04.2018',
'branch' : …
```
=> Adding --buildinfo arguement to hubble

hubblestack/extmods/returners/splunk_nebula_return.py
Example of exception log:
2018-06-14 16:32:04 [salt.loaded.ext.returner.splunk_nova_return][INFO    ] Error establishing connection to splunk server https://bad-host:8088/services/collector/event failed: ('Connection aborted.', gaierror(-2, 'Name or service not known')
Fixes #403
=> Hec exception handlers

hubblestack/extmods/modules/nebula_osquery.py
@sumanmehta This is an important change for you to review, as you must make sure your nebula queries are migrated before the next version.
The reason for this change is we want the ability to override specific queries using nebula.top and the top.nebula file.
=> Nebula per-query overrides

hubblestack/daemon.py, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
I am extending the change made in https://github.com/hubblestack/hubble/pull/402 to all dev Dockerfiles 
FYI, earlier I was going to change the behaviour of --version command as mentioned on slack. But now we have dropped that idea. So this PR involves changes in Dockerfiles only.
=> Changing Dockerfiles to pickup hubble_buildinfo file from /data mount

pkg/dev/centos7/Dockerfile, pkg/dev/centos7/pyinstaller-requirements.txt
The dep version bumps are mostly minor version releases that only address git cve's released earlier this year.
=> dockerfiles: minor version bumps for osquery and deps 

conf/hubble, hubblestack/daemon.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
Also brings all the returners in line for requests error handling
Defaults for the retries are 3 times with 15 seconds between. Retries
are on a per-batch basis.
=> Add optional retries to splunk returners

hubblestack/daemon.py
This will prevent unintentional interference of files in /srv/salt
=> Remove default file_roots

hubblestack/extmods/modules/nebula_osquery.py, hubblestack/extmods/modules/win_pulsar_winaudit.py
When I first added this function from salt, I apparently caught this
recursive reference in two files, missed it in two others. Anyway,
our new nebula data format hits it when merging files via the topfile.
=> Fix some copy pasta

hubblestack/extmods/modules/nebula_osquery.py
Currently, some passwords are also getting logged by hubble osqueries. 
This PR aims to mask such passwords by using mask.yaml file. See PR in hubblestack_data for more details:
https://github.com/hubblestack/hubblestack_data/pull/119
There are two ways in which passwords are being printed:
1) Some passwords are being passed as command line arguemnts. For example "command_line" column of 'running_procs' contains some passwords in some cases.
2) Some passwords are injected as environment variable, and hence logged under 'environment' column of 'running_procs' for example.
Passwords of type 1 can be handled by "blacklisted_strings" part of mask.yaml.
Passwords of type 2 can be handled by "blacklisted_objects" part of mask.yaml.
DO NOT MERGE. 
( still need to test a few scenarios )
But …
=> Mask nebula passwords

hubblestack/daemon.py
It makes sense to not allow this for the central logging, but I can't see the
harm in altering the console logging.
=> I sometimes desire to change the console log format.

pkg/windows/dockerfile
Following changes have been made in windows docker file:
1. Earlier, PortableGit was extracted in a wrong location. Fixed now.
2. Upgraded the salt version being used to 2018.11
3. If 'opt' folder is present in mounted location, it's contents are inserted into the build.
4. If 'hubble.conf' is present in the mounted location, it's content are inserted into the build.
5. SHA256 is calculated for the generated build.
=> Improving windows docker file

pkg/windows/dockerfile
Osqueryi was being placed at wrong location in windows docker file earlier.
So osquery was not running.
Fixing the same.
=> Putting osquery in right place in windows docker file

hubblestack/daemon.py
This will hopefully help with issues we've seen around hubble not restarting properly.
I can think of only two reasons that the restart wouldn't happen properly:
1. Hubble is hung. Not only is this uncommon, but assuming the pidfile is still in place, hubble will try to kill the previous process before starting, and will then refuse to start, so assuming the pidfile is in place, there will still only be one running hubble process.
2. The pidfile is gone or has been moved
This PR should alleviate the second issue.
=> Write the pidfile once per minute

.travis.yml, pylintrc, test-requirements.txt, tests/travis-runner.sh
This requires further discussion.
I turned this on for my personal CI. You can see the last build output here: https://travis-ci.org/jettero/hubble
I've had some luck applying autopep8 to the source files, but that really doesn't resolve everything (or even most things).
The pylintrc is just the Salt pylintrc with very little (if any) modification. I think there's quite a few things we can remove and we'll probably want to tune the policies that it's checking.
=> pylintrc and travis-ci yaml

hubblestack/daemon.py
unless the configuration option is not explicitly configured
the default set of grains are emitted
=> add logic to configure the grains to be emitted to syslog

hubblestack/extmods/returners/sqlite.py
$ __python3 -c "0755"__  # --> SyntaxError: invalid token
$ __python2 -c "print(0755 == 0o755)"__ # --> True
=> Python 3 syntax error: 0755 --> 0o755

.travis.yml
Repo switch must be turned on at https://travis-ci.org/hubblestack
=> Travis CI: Run tests in parallel on Python 3 in allow_failures mode

hubblestack/extmods/modules/win_pulsar.py, hubblestack/extmods/modules/win_pulsar_winaudit.py
Python 3 will treat __\U__ in a string as a Unicode escape and will raise a syntax error so let's use an r'string' instead of a normal 'string'.
* $ __python3 -c "print('\U')__   # SyntaxError: (unicode error)
* $ __python3 -c "print(r'\U')__  # __\U__
=> Python 3 syntax error: '\Users:' --> r'\Users:'

hubblestack/daemon.py, hubblestack/extmods/modules/fdg.py, hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/hec/obj.py, hubblestack/hec/opt.py
The returner for FDG has to be much more flexible than other returners because we don't know in advance in what format the data will be.
Here are the design requirements:
* Data formed as a list should be put in multiple events
* All events should have an identifier, which is a normalized fdg file name
* fdg.top results should be handled as if fdg.fdg were called on the individual files. The splunk events will look the same either way
In the process I had to tweak the return structures for the fdg system, but I think it's better for it.
I also removed the empty field stripping from the `hubblestack.hec.obj.Payload` class -- it was stripping in such a way that there were side effects, and really we only want to strip at the top-level of the event anyway in most cases -- something which is …
=> FDG splunk returner

hubblestack/hec/obj.py
* the misc exception catch fails to log anything (but almost never comes up anyway)
* if the status is >= 400, the message was requeued regardless of the reply; fixed to discard if the message is malformatted (and log the fact), or to requeue on other errors unknown --- and in either case, we log as much of the reply as possible for later analysis
* the check for `if self.log_other_exceptions` is flawed (no such settting exists)
=> fix various bad error handlings in the hec.obj

hubblestack/daemon.py
With this patch, if you insert yaml syntax errors in your config, hubble (actually Salt) will inform you of the errors before sys.exit.
Previous to this patch, Salt would log to the salt Null logger and sys.exit without comment.
(possibly should submit something to Salt too)
=> Minor logging issue

hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/hec/__init__.py, hubblestack/hec/dq.py, hubblestack/hec/obj.py, hubblestack/hec/opt.py, hubblestack/splunklogging.py, pkg/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/centos6/pyinstaller-requirements.txt, pkg/centos7/pyinstaller-requirements.txt, pkg/coreos/pyinstaller-requirements.txt, pkg/debian7/pyinstaller-requirements.txt, pkg/debian8/pyinstaller-requirements.txt, pkg/debian9/pyinstaller-requirements.txt, pkg/dev/amazonlinux2016.09/pyinstaller-requirements.txt, pkg/dev/centos6/pyinstaller-requirements.txt, pkg/dev/centos7/pyinstaller-requirements.txt, pkg/dev/coreos/pyinstaller-requirements.txt, pkg/dev/debian7/pyinstaller-requirements.txt, pkg/dev/debian8/pyinstaller-requirements.txt, pkg/dev/debian9/pyinstaller-requirements.txt, pkg/windows/pyinstaller-requirements.txt, pyinstaller-requirements.txt, requirements.txt, setup.py, tests/unittests/test_hec_dq.py
* removed diskcache, which uses sqlite3 (I feel like that's asking for trouble)
* refactored the http_event_collector options processing (more DRY is good)
* added some options @fossam wanted (compression, location, size of the diskqueue)
* fixed a missing log.error() when send fails without being an urllib3 exception
* found a major bug that prevented flushing the diskqueue; which without flushing is just a catalog of failure that never clears
=> Queue improvements

hubblestack/extmods/grains/cloud_details.py
There are some AWS accounts with leading 0's, which this method breaks. Leave it as a string, but still do the type casting to check for errors.
Thanks @tbennett0
=> Don't reassign aws account id after attempting to cast as int

hubblestack/__init__.py, hubblestack/daemon.py, pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile, pkg/windows/dockerfile
This PR aims to provide a better way to identify if a build was created with a proper git tag, or if it was created with the code in develop branch.
All suggestions are welcome. I have given some explanations along the code.
My idea is :
To distinguish the build from inside ( i.e. after installing it ), we will use "hubble --buildinfo" command. It will provide a lot of info.
In order to know about the build before installing it, we can have a look at its iteration number. I good production build should have 1,2,3,... like iteration number. A huge and weird number indicates that it is not meant for production.
=> Distinguish between real and develop build

hubblestack/extmods/grains/systemuuid.py
On some hosts, system_uuid isn't generated, and osquery creates a random value every time. If that's happening, we should fallback to the cached hubble_uuid value.
=> Fallback to hubble_uuid if system_uuid isn't consistent

hubblestack/extmods/modules/hstatus.py, hubblestack/extmods/returners/splunk_generic_return.py, hubblestack/hec/obj.py, hubblestack/status.py
I'm not totally sure if we should call this a work in progress, or if @fossam will want changes to how the counters submit; but this is totally working for me with the below query.
(NOTE: do not actually do the below if your dataset is at all bigger than about a few thousand events... that O(N²) map search will kill your Splunk)
```
index=hubble sourcetype=hubble_hec_counters 
| table index stype count start end 
| dedup stype
| map search="tstats count as actual where index=$index$ sourcetype=$stype$ earliest=$start$ latest=$end$ | eval reported=$count$ | eval stype=\"$stype$\"" maxsearches=100
| fields stype actual reported 
| eval diff=abs(actual-reported)
| sort -diff
```
=> message submission accounting

hubblestack/daemon.py, hubblestack/status.py
As requested in https://jira.corp.adobe.com/browse/CSTTEAM-44470, this logs major signals to splunk when received.
Note that it doesn't log SIGALRM since we use that internally for setting interrupt timers on things that might hang (such as grains refreshes).
Future editions of this functionality could use a library like 
https://github.com/larsks/python-signalfd to get more information about where the signal came from, and could also do some HASATTR magic to catch all the signals supported by a given system. (I only included the most common)
Talking to @fossam he thinks we should just hold off until we can include that additional information, but since I was already mostly done with the code I figured I'd submit this PR for discussion. Thoughts?
=> Log major signals to splunk

pkg/windows/hubble.conf
I don't know how this got here. We handle the defaults in daemon.py.
Submitting against 3.0 branch since this is a bugfix.
Fixes #513
=> Remove bad cachedir and log_file definitions from windows config

hubblestack/daemon.py, hubblestack/extmods/returners/splunk_generic_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/utils/stdrec.py
This seems to do the job @fossam was asking for (adding std host fields).
I attempted to split out the generation of the std host fields from splunk_pulsar_return; with the intention of literally standardizing those fields generation between the various splunk returners. (not totally sure that's a great idea, comments welcome).
=> More counter fields

hubblestack/daemon.py, hubblestack/extmods/grains/systemuuid.py
This makes a handful of small changes to address a corner case: If Hubble is installed on a system and run at least once, a hubble_uuid cache file is generated. If this system is then cloned (an AMI is made, for example), the cloned systems will all have the same hubble_uuid. This attempts to work around that by first checking the system_uuid to see if the current system value is different from the cached value. If it is, it invalidates the hubble_uuid cache.
- Start caching the system_uuid grain to a file, similar to hubble_uuid
- Copy system_uuid into `__opts__`
- Add logic to theload_config function to detect cloned systems and delete the hubble_uuid cache file in those cases.
=> Attempt to detect cloned hubble installs

hubblestack/extmods/grains/hubbleversion.py, hubblestack/extmods/modules/nebula_osquery.py, pkg/windows/osqueryd_safe_permissions.ps1
Following changes are made:
- Added support to dynamically generate osquery conf in JSON format using topfile. One can now create host specific osquery conf using grains
- Added support to dynamically generate osquery flagfile using topfile. One can now create host specific flagfile using grains. This can be especially helpful if we want to enable/disable certain setting on certains host(s) or enable/disable extensions on few hosts.
- Added buildinfo in grains
=> Enhancing nebula to generate osquery conf from yaml files

hubblestack/extmods/modules/pulsar.py
I had briefly toyed with using deep copy to prevent modifying `__opts__` but decided that was fine and fine to log to splunk.
I also toyed with a global pattern database, etc, but finally found the problem was with the list merge in the config combiner logic.  This small patch fixes a rather large (over time) memory leak ... and probably a CPU leak (if there is such a thing); re-re-re-considering patterns for exclusion is certainly something like a CPU leak.
=> fix memory leak in pulsar

hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_osqueryd_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/splunklogging.py, hubblestack/utils/stdrec.py
I think the idea is that, for anything listed in the config file under {splunk_index_extracted_fields}, we find the value in the event, then stick it in {fields} with {meta_} prepended to the name. @fossam, that's what we were thinking, right?
I think this does it, but @jettero, you might want to double check I didn't miss anything.
=> Add meta_ to all index time extracted fields

hubblestack/daemon.py, hubblestack/extmods/modules/hstatus.py, hubblestack/status.py, tests/unittests/test_counters.py
There's a new setting "bucket_len" for "hubble_status". It defaults to 3600. The idea is to drop the counters into clock-aligned buckets so they're easier to line up with splunk counts by time. If the periods are predictable, then all the accounting is that much easier.
I think I increased the tech-debt a bit as this is pretty hard to read now; but it's worth it as it'll be a zillion times easier to line up with splunk event counts in searches.
I'm still testing this. (Should I add myself as a reviewer?)
=> updated counters with buckets

hubblestack/daemon.py
The escapes for those flags come before `__salt__` is defined (by design). We want to short-circuit and exit gracefully.
=> Properly handle cleanups for --version and --buildinfo

hubblestack/daemon.py
This needs to be done since `cloud_details` is a dict holding `cloud_instance_id` and `cloud_account_id`.
Changed some grains for more useful data in syslog.
=> fix for emitting syslog messages in case a grain is a dict

hubblestack/daemon.py, hubblestack/extmods/modules/conf_publisher.py, hubblestack/log.py, hubblestack/status.py
We found a memory leak in the salt logging system which I then confirmed with some of the salt engineers. Rather than wait for the fix, I just pulled salt's logging out, and consolidated our logging into hubblestack/log.py
It resulted in much cleaner setup and cleaned up some of our direct-to-splunk emitting elsewhere.
And it's working great!
=> Remove salt logging and consolidate logging system

hubblestack/extmods/modules/nebula_osquery.py, hubblestack/splunklogging.py
No need for these manual instances now that we have
hubblestack.log.emit_to_splunk
Note, these will now show up under different logger names in splunk --
rather than logging under the module name, they will log under the
new names `hubblestack.osquery_timing` and
`hubblestack.osquery_disk_usage`.
=> Remove splunklogging.emit_data

hubblestack/extmods/grains/cloud_details.py
* get rid of gcp attributes, it can blow up the grains
* move extra details to their own try-except so we're guaranteed to get the limited details even if there's a problem with the return values of the extra details
* add azure extra details, prohibitive to correlate these details through other methods due to less than stellar api design.
=> Fossam cloud details fix

hubblestack/daemon.py
This one is a gnarly one. Since the hubble_version and buildinfo are on disk, and grains refresh *from* disk, an old version of the daemon could pick up changes to those thing on disk (perhaps from a new package install) and if you're using those grains as reporting tools, you lose insight into what is actually running on the host.
This PR makes those grains persist automatically across refreshes. But additionally it adds a new hardcoded grain `hubble_marker_3` so you can tell if a daemon is actually running the new persisting code or not. It's a hacky solution but I don't have a better one in mind.
Thoughts?
(Note, this is targeted directly at 3.0 and will hit develop when I merge forward)
=> Persist version/buildinfo grains and add hubble_mark_3 grain

hubblestack/files/hubblestack_nova/win_secedit.py
This will allow using the user/group name in checks where a user or group must be present in a list, but other items are allowed in the list.
=> Add support for account_contains in win_secedit.py

hubblestack/extmods/modules/hstatus.py, hubblestack/status.py, tests/unittests/test_counters.py
* remove the old reset system. The memory anit-leak max-bucket limits should be enough
* remove logic that checks last_t/first_t in buckets; vestigial and not really applicable
* convince status.py to return all buckets with keyword 'all' — formerly skipped current bucket (why?)
* teach hstatus.py extmod to consider last_t as a filter, "have I already sent this?" Later, it should be asking, "have I sent this twice?" (Or perhaps thrice, or probably by `__opts__`) Repeating the information is desirable, particularly if we think things really do go missing.
This should produce really accurate counts and it should stop skipping buckets. It was really difficult trying to figure out why so many buckets were missing. So much was working that it literally took days to figure out why the missing …
=> Missing counters

hubblestack/hec/obj.py
We should be explicit here to avoid accidentally using certs where we've told
it we don't want to. Probably only applicable in my lab at home, but I think
there's other places this could be useful sometimes (or perhaps temporarily).
=> The default is to use certs.

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/debian7/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/hubble-autostart
@praksinha This undoes your work in #474. We had some users that didn't like that we were adding cronfiles as part of install. Additionally, with the memory leak fixes from @jettero, we no longer need the restart anyway.
I have kept the logic in place as an optional inclusion, if the autostart script is copied to the local build directory (for the `start`).
=> Make the cronfiles optional (not included by default)

hubblestack/hec/obj.py
This prevents some annoying duplication of queue(start) messages. I thought it was in the previous PR.
=> minor bug in queue(start) message

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
Following are fixed in this:
- There were directories and files getting created and packaged with hubble installer that were not used by Hubble. Example: we include /etc/osquery/osquery.conf and /etc/osquery/osquery.flags file but never use it via hubble. Similar we create directories /var/log/osquery which is never used by Hubble. Removed all such directories.
- Added few RPM metadata fields like URL, Description and Summary. This would improve YUM repository support for rpm packages.
=> Removing unused directories from package and adding rpm spec metadata

hubblestack/extmods/modules/hstatus.py, hubblestack/status.py
Fixing the dup hec summary messages has the unintneded side effect of ensuring no repeat messages are ever submitted. So this change also submits intentional repeats (adjustable via `hubble_status:summary_repeat` in `__opts__`).
=> attempt to fully fix dup hec summary messages

hubblestack/hec/obj.py
We need to know precisely what's causing the mysterious "presumed minor" errors. I suspect it's not actually something form the two lines (one is an assignment, so one line really). I suspect the "maximum recursion" errors are actually text strings from something out there on the web -- but I just don't know.
So I just turned on traces for the error. I think the "presumed" class errors are rare enough that we should just leave the traces here.
=> I tried a lot of stuff here. This is the best solution imo.

hubblestack/hec/opt.py
look for `disk_queue*` at the top of config. It seems to work, and should be backwards compatible with other differing settings in the per-hec settings area(s)
=> Disk queue set top of file

hubblestack/hec/obj.py
Basically easy to reproduce... fairly major bug.
Most of the time the _direct_send_msg() will trigger a new queue flush. In the best case, it does seem to resolve itself somehow; but in the worst case, it opens enough connections to splunk to trigger a max connections error (O_o).
=> move flushing_queue = True above _direct_send_msg() 

pkg/windows/dockerfile
This dockerfile does not work any more  because mircosoft has depercated the "latest" tag which we were using to pull windowservercore.
See the bottom part:
https://techcommunity.microsoft.com/t5/Containers/Windows-Server-2019-Now-Available/ba-p/382430
In other words, you can't make any new windows build using current Dockerfile ( unless you have already cached windowsserver in the past ).
@basepi 
Let me know if I am supposed to raise PR for develop branch also.
=> Using ltsc2016 tag in win dockerfile

pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
#CAN BE MERGED
I am changing Dockerfiles so that one can build osquery from custom code as well.
This behavior is governed by the docker build argument "OSQUERY_BUILD_ENV"
By default, its value is "remote". In this case, docker will bring the osquery code from the GIT url specified in the Dockerfile.
If its value is "local", then docker will try to copy "osquery" folder into the image. So you should place your osquery code in a folder name "osquery" and this folder should be located in the same directory that contains Dockerfile.
On using "--build-arg=OSQUERY_BUILD_ENV=local", osquery is built from the custom code and packed into the hubble build.
This change uses "multi-stage" feature of docker, so this dockerfile will run on docker 17.05 or later version.
Refer this : …
=> Provision for building osquery with custom local code

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
I've tested Cent6 with good results. Going to let the rest be tested through Jenkins -- I figure if it builds on something old like Cent6, there's a good chance it will work everywhere. We haven't had to make as many one-off exceptions with these dependency builds.
=> Update git and curl

hubblestack/splunklogging.py
Don't let the two line change fool you; I tried a lot of stuff. Inside the hubble binary, there's no way to recover the `'pathname'` attribute (it's always `'logging/__init__.py'` for some reason).
This actually works though, as long as people are using `logging.getLogger(__name__)` in the dangerous files.
=> use 'name' instead of 'pathname' in the splunklogging filter

hubblestack/extmods/modules/safecommand.py
This way we can protect the system from a poorly-tested command.
=> Add timeouts to safecommand.run

hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_generic_return.py, hubblestack/hec/obj.py, hubblestack/hec/opt.py
the mysterious default indexing ... is a null index field.
I think there's still a couple returners (including my own generic return) that don't use `make_hec_args()`; the other is fdg.
Arguably the hec.obj should check for missing index and set it to the new `self.default_index` when missing.
=> add default_index to hec.obj

hubblestack/extmods/returners/splunk_fdg_return.py
Since index-extracted fields are handled in stdrec.py, we can
probably remove these references everywhere. But as of now, all the
other returners still have this cruft, so I'm adding it back here. `cloud_details` can also probably be removed everywhere as well.
@jettero I'll probably have you clean all of these up for our next release.
=> Match the cruft between returners

pkg/hubble.service, pkg/source/hubble.service
This change has two driving reasons. The first is that the StartLimit
directives have changed in recent versions of systemd. In some versions
it's expected in the `[Service]` section, in others in the `[Unit]`
section. Additionally, it's also been renamed to `StartLimitInvervalSec`
in recent versions of systemd.
Rather than deal with these compatibility issues, I propose that we
remove them. I have also bumped the `RestartSec` to 300. Basically, if
hubble ever crashes, we do want it to restart, but we're not in a hurry.
So I think using `RestartSec=300`, the impact of trying to restart
hubble forever is negligible, and we save ourselves the hassle of trying
to deal with systemd compatibility.
Thoughts? I think @praksinha added these in.
=> Remove StartLimit directives in systemd unit files

pkg/windows/dockerfile, pkg/windows/osqueryd_safe_permissions.ps1
Following changes:
- Pinned osquery version to v3.3.2. This was required since facebook has released a new 3.4.0 version of osquery specifically for Windows.
- Fixed permissions of osquery for Windows server 2019. New permissions (explicit DENY) apply to all supported Windows platforms.
=> Fixing osquery permissions for Windows server 2019

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/coreos/Dockerfile
Making changes in Dockerfiles similar to https://github.com/hubblestack/hubble/commit/890463de97766349977466e0e6b13109a9f3d5a1
After this change, one can build hubble with custom osquery code.
@basepi I have made these changes in just centos7 for now. Please answer these questions so that I can proceed to make these changes for all OS:
1. Is '3.0' the correct branch to make these changes ? I am assuming that the changes made here will propagate to 'master' branch Dockerfiles so that we can build hubble 3.0 using master Dockerfiles.
2. What should be the value of OSQUERY_SRC_VERSION ? ( see the comment in code for more details )
3. I have just focused on bringing the changes from 'dev' to 'pkg' dockerfiles related to the aforementioned commit for now. If there are any more changes which …
=> Provision of custom osquery build in Dockerfiles

hubblestack/utils/stdrec.py
This would only happen if a host had a `localhost` domain so I didn't
spot it until today
=> Add missing import

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile
Hi @basepi ,
I noticed that I made another mistake in my old PR https://github.com/hubblestack/hubble/pull/527
The idea behind PR 527 was to be able to distinguish between builds created from pkg and dev Dockerfiles. I am quoting a comment from old PR 527 :  
```
'branch' and 'last_commit' will be populated in the docker build step.
If you use the "pkg" dockerfile, you will end up with
{ 'branch' : '2.4.7' , 'last_commit' : 'TAGGED_BUILD' }
If you use the "pkg/dev" dockerfile, you will end up with
{ 'branch' : 'develop' , 'last_commit' : 'v2.4.7-197-g83ef7c0' }
```
But it seems that I made the corresponding change only in debian9 Dockerfile.
( So if I build centos7 from pkg Dockerile now, I will get some hash in 'last_commit' field. But I want it to show 'TAGGED_BUILD' in 'last_commit'). …
=> Avoiding last commit info in master builds 

pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile
Replacing underscore with dash to make debian build name similar to other os name.
I should have pushed this change in https://github.com/hubblestack/hubble/pull/638
But I caught this discrepancy in build names later.
=> Renaming debian builds

pkg/centos6/Dockerfile
Hi @basepi 
I made a mistake in my old PR https://github.com/hubblestack/hubble/pull/527
Basically I broke the pyinstaller command. So I am not able to create builds for centos6 ( from pkg Dockerfiles ) anymore.
This PR should fix it.
Thanks.
=> Correcting the pyinstaller command in centos6 Dockerfile

hubblestack/extmods/returners/graylog_nebula_return.py, hubblestack/extmods/returners/graylog_nova_return.py, hubblestack/extmods/returners/graylog_pulsar_return.py, hubblestack/extmods/returners/logstash_nebula_return.py, hubblestack/extmods/returners/logstash_nova_return.py, hubblestack/extmods/returners/logstash_pulsar_return.py, hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_osqueryd_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py, hubblestack/extmods/returners/sumo_nebula_return.py, hubblestack/extmods/returners/sumo_nova_return.py, hubblestack/extmods/returners/sumo_pulsar_return.py, hubblestack/splunklogging.py, hubblestack/utils/stdrec.py
This is a holdover from hubble-salt and is no longer needed. We don't
use or care about masters, and it always defaults to 'salt' anyway.
=> Remove 'master' from all returner events

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile
Reverts hubblestack/hubble#646
@yassingh After chatting with @fossam he thinks it's harder to work with the last_commit field in splunk when it's a special string like this.
I also did some testing, and if you're on a tag, `git describe` just returns the tag itself:
```
basepi@mustafar:~/src/work/hubble$ git checkout v3.0.1
Note: checking out 'v3.0.1'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
git checkout -b <new-branch-name>
HEAD is now at 39c7491 Rev to v3.0.1 …
```
=> Revert "Avoiding last commit info in master builds "

hubblestack/extmods/modules/pulsar.py
Fixing a minor bug here.
Pulsar calls the "update" function once every 5 minutes. But in the update method, 'paths' attribute is lost.
But fortunately, the 'paths' attribute is set as soon as ConfigManager constructor is called ( this happens at this line https://github.com/hubblestack/hubble/blob/develop/hubblestack/extmods/modules/pulsar.py#L715 ).
And luckily, this constructor is being called every second.
The problem arises if a fim event is generated and this line ( https://github.com/hubblestack/hubble/blob/develop/hubblestack/extmods/modules/pulsar.py#L767 ) is hit within that second.
**How to reproduce the error:**
Just start a script to create fim events very fast ( once every 0.4 seconds worked for me ).
And you will see this error every 5 minutes:
```
2019-06-05 08:59:55 …
```
=> Saving 'paths' from vanishing in update ( pulsar )

hubblestack/hec/obj.py
As pointed out by @praksinha 
urllib3.ProxyManager in line number 204 is expecting the proxy to be a string ( and not a dictionary ).
Make a change to fix this.
The is the error which a user gets if try to use a proxy with the current code:
```
An Error occurred while loading the config: expected string or buffer
01:29:52 [ERROR] An un-handled exception was caught by salt's global exception handler:
TypeError: expected string or buffer
Traceback (most recent call last):
File "hubble.py", line 5, in <module>
File "hubblestack/daemon.py", line 58, in run
File "hubblestack/daemon.py", line 700, in load_config
File "hubblestack/log.py", line 148, in setup_splunk_logger
File "hubblestack/splunklogging.py", line 72, in __init__
File "hubblestack/hec/obj.py", line 204, in __init__
File …
```
=> Fixing an issue with proxy in hec

hubblestack/extmods/grains/systemuuid.py
Still warns for _undefined variable_ and _broad exception_
=> fix linting errors for grains/systemuuid.py

hubblestack/extmods/grains/hubbleuuid.py, hubblestack/extmods/grains/systemuuid.py
I was thinking here instead of `Exception`, it would work with `(OSError, IOError)` since it's for the `open()` clause but I'm not entirely sure so I left it like this to be safe
=> Fix linting for hubbleuuid.py

hubblestack/extmods/grains/splunkconfig.py, hubblestack/hec/opt.py
Somewhere along the way to 3.0.1 build, hubble lost its ability to pickup splunk configuration dynmaically.
As a result, hubble needs to be restarted if we intend to update the splunk config.
Some of our functionalities are dependent of this feature.
Making some changes in this PR to add that functionality back to hubble.
In this PR, I am recreating the file which was deleted in https://github.com/hubblestack/hubble/pull/580
Moreover, I am changing the hec/opt.py file so that first it looks in grains,get for splunk config ( and then fallback to config.get ),
=> Re-adding the ability to read splunk config from hubble.d

conf/hubble, hubblestack/extmods/grains/splunkconfig.py
Some users were still on the old-style splunk returner config
and were missing this grain. We can fix that in the config, but we
decided we wanted to make sure this grain was bulletproof. If the config
exists, we populate the grain.
=> Automatically populate the splunkindex grain

hubblestack/daemon.py, hubblestack/extmods/modules/conf_publisher.py, hubblestack/log.py
After this PR : https://github.com/hubblestack/hubble/pull/679 , splunk config loaded via hubble.d/*.conf will become a part of __grains__.
As a result, splunk related details will be published on spunk, including the token.
So I am trying to omit token ( and other such sensitive details ) from splunk logs.
Instead of writing completely new logic, I am reusing some functions which were present in extmods/modules/conf_publisher.py 
I have made more comments in the PR for explanation.
=> Avoiding splunk token from getting logged among grains 

conf/hubble, hubblestack/daemon.py, hubblestack/extmods/modules/fdg.py, hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_osqueryd_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
It was broken in the splunk returner consolidation, and the need for
this retry system has been eliminated by the disk queueing system
anyway.
=> Remove returner_retry functionality

.gitignore, hubblestack/daemon.py, hubblestack/extmods/audit/grep.py, hubblestack/extmods/modules/audit.py
The new audit module shares a lot with the previous generation (nova). I cut out a few things that I don't think were getting much use (like controlled checks and compliance % calculations). If we decide we have uses for them, they would be pretty trivially easy to add to the new module.
I also added a couple of new features, `target` and `version`. Check out the docs in audit.py to get a feel for how they work, and keep me posted if you have any questions.
So far I have only ported a single module to the new system, grep.py. As you can see, the actual audit modules themselves are *vastly* simplified compared to nova. Porting the rest of them should be pretty trivial.
***
Two other missing pieces:
* Code to convert the old profiles to the new format. This code will be module-specific …
=> New audit.py module to replace nova (hubble.py)

hubblestack/extmods/modules/conf_publisher.py, hubblestack/extmods/returners/splunk_fdg_return.py, hubblestack/extmods/returners/splunk_nebula_return.py, hubblestack/extmods/returners/splunk_nova_return.py, hubblestack/extmods/returners/splunk_osqueryd_return.py, hubblestack/extmods/returners/splunk_pulsar_return.py
I have mixed feelings about this. The problem is clearly with how `_nick` functions and the docs that surround it. But rather than fix that, which is hard, I just fixed the usage of it in the returners that use it.
In particular: we want to make sure if `sourcetype_nebula` is undefined that it gets the intended default.
=> defaults fix

hubblestack/extmods/fdg/process.py, hubblestack/extmods/modules/fdg.py
This will allow `return: splunk_fdg_return` to work within FDG runs.
=> Fix intermediate return handling for splunk_fdg_return

hubblestack/extmods/fdg/grep.py, hubblestack/extmods/fdg/osquery.py
py2 was particularly bad with args, kwargs and *args (particularly mixtures of them). They mostly fixed that in 3.0, but for now, It's best to just remove the variadic args to keep from confusing the args population.
* fixed in fdg/grep.py
* fixed in fdg/osquery.py
=> variadic args fixes

conf/hubble, hubblestack/hec/opt.py, hubblestack/log.py
Initially the user had to provide the whole block of parameters in /etc/hubble/hubble.d/user.config with a format similar to the default config block in /etc/hubble/hubble. Now the user can specify only the index, token and port in /etc/hubble/hubble using the global parameters splunk_token, splunk_index and splunk_port. These options will be given priority over the hubblestack:returner:splunk block. Index and token must be specified together or not at all.
=> Adding support for overriding splunk configuration via global parameters

pylintrc
I know all the globals should be allcaps, but as long as I've been writing programs, allcaps has meant "constant" not "global".
I've seen `log = logging.getLogger(__name__)` as a global a billion times. I've never seen it as `LOG`. I think that's just a side effect of the pylint defaults.
I'm wondering if there's other things we should consider changing in the pylintrc.
=> `log = logging.getLogger(__name__)`

conf/afterinstall-systemd.sh, conf/afterupgrade-systemd.sh
Hubble service is disabled on few operating systems post install. If instances restart, then user needs to explicitly start the Hubble service.
=> Enabling hubble service post install on systemd init

.gitignore, hubblestack/hec/dq.py, tests/unittests/test_hec_dq.py
I was experimenting with semi-large queues and discovered that the O(n²) operation of counting the disk usage on every `pop()` is (gasp) expensive. Probably estimating the disk queue size on a `pop()` will rarely ever matter, and probably saves us a ton of CPU time.
In fact, we can do roughly the same thing to `get()` and `put()`.
We leave counting disk space completely to `__init__()` and `getz()` — `getz()` gets as many messages as will fit in the splunk max message size.
=> CPU improvements in diskqueue pop()/get()/put()

hubblestack/hec/obj.py
When hubble receives 403 from Splunk HEC the issue is hard to discover through the logs (debug level).
According to the docs, that would be an expired/invalid token and needs appropriate logging.
https://docs.splunk.com/Documentation/Splunk/latest/Data/TroubleshootHTTPEventCollector#Possible_error_codes
=> add logging for invalid/expired splunk tokens

hubblestack/extmods/returners/splunk_fdg_return.py, tests/unittests/test_fdg_sourcetypes.py
Apparently we do want to extend the sourcetype name from `hubble_fdg` to `hubble_fdg_filename` but let's choose to do that without the `salt://` protocol and without the `.fdg` file extension; while we're at it, make sure to replace all non alphanumerics with an underscore.
=> fix: sourcetype = 'hubble_fdg_' + fdg_file

pkg/hook-hubblestack.py
pyinstaller only installs package deps for items that are imported at initial runtime
The workaround is to specify packages for "hidden import"; they get packed into the binary so later when `fdg/readfile.py` is lazy loaded, it can still absolute import `hubblestack.utils.encoding`
I tested this by building my own el7 rpm without the hidden import (readfile.json crashes) and with the hidden import (readfile.json functions).
=> instruct pyinstaller to include encoding utils

hubblestack/extmods/grains/cloud_details.py
IMDSv2 requires a session-based token to authenticate to the metadata service. Hubble will now generate a token and use it to fetch metadata values.
=> adding support for IMDSv2 for aws

tests/unittests/test_process.py
I think the main requirement in terms of style for unittests should be readability and the guidelines that I think would help write better unittests are:
- tests should be named `test_<function_name>_<does_this>_<when_this>`
- one concept per test, the _one assert per test_ rule is too restrictive but modularity would work beautifully
- be explicit: although `assert status` would work just fine, we expect status to be True so the test should be verbose about it
- the `expected_ret` should be the first part of a comparison, for better readability in case of failure
- an error message would be great for asserts but no need to go overboard
They're up for debate and feedback is more than welcome. 
Something I am unsure of:
-  Does it make more sense to have an `expected_ret` and test `assert …
=> Clean unittest

tests/unittests/test_grep_nova.py, tests/unittests/test_nebula_osquery.py, tests/unittests/test_pkg_nova.py, tests/unittests/test_process.py, tests/unittests/test_process_status.py, tests/unittests/test_pulsar.py, tests/unittests/test_readfile.py, tests/unittests/test_ssl_certificate.py, tests/unittests/test_stat_nova.py, tests/unittests/test_time_sync.py
First of all, you're not supposed to modify the path in your tests. There's a discussion on the pytest site about it... https://docs.pytest.org/en/latest/pythonpath.html#invoking-pytest-versus-python-m-pytest
Second, we do this in conftest anyway (even though we really shouldn't):
https://github.com/hubblestack/hubble/blob/develop/tests/unittests/conftest.py#L21
Lastly, if you really don't want to have to tyep `python  -m pytest tests/unittests` or whatever, you can use pytest-pythonpath (see comment in pytest.ini 
We should really remove the sys.path hackery from confest too, but ... this small step is just the right thing to do
=> wrong path hacking in test files

hubblestack/extmods/modules/hubble.py
Python 3 doesn't allow dict to be modified while iterating over it, raising an error. This fixes that by iterating over a copy of the keys instead and removing the items from the actual dict.
=> fix py3 audit bug

hubblestack/extmods/modules/pulsar.py, tests/unittests/test_pulsar.py
If we watch a single file with pulsar ... we may forget to watch it again later... we may miss events relating to the file...
This attempts to address all those problems.
Note that in any case it's impossible to watch a file that's not there using inotify (kernel stuff). So if we're not watching a file, we have to notice on the next `process()` pass and the best we can do is generate a pretend IN_CREATE event.
=> Fim single file

hubblestack/files/hubblestack_nova/openssl.py
`time.strptime` expects type `str` and doesn't accept `bytes` anymore, failing with a `TypeError`. This fixes that problem by decoding the bytes into string
=> fix bug in hubblestack_nova/openssl.py 

hubblestack/daemon.py
if the configfile doesn't exist, setting file perms to 384 (aka 0o600, aka rw-------) will raise a FileNotFoundError.
This is a reasonable fix for that.
=> fix minor clean-install bug with configfile permissions

hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/utils/s3.py
S3 cache expire can now be configured through the hubble stack config('s3.cache_expire'). Default cache expire time increased from 30 seconds to 1800 seconds(30 minutes). Also handles s3.query return DELETE request properly.
=> S3 fix limit

pkg/windows/dockerfile, pkg/windows/hubble-Setup.nsi, pkg/windows/hubble_config_permissions.ps1
- Added support for TLS, TLS11, TLS12 for downloading from chocolatey URL.
- Added a new script 'hubble_config_permissions.ps1' for restricting permissions of '\etc\hubble' folder in windows. Only system and admin users are allowed full control.
=> Changing permissions for hubble config in windows + other changes in 3.0 branch

pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/coreos/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
Because the `v3.0.8` and `v3.0.9` tags are unsigned, `git describe` is giving build info of, "`v3.0.5-573-g03e55c8`" ... while technically correct... `v3.0.9` is `03e55c8` and it's `573` commits after `v3.0.5` ... this isn't really a desirable description.
I propose we use `git describe --dirty --always --tags` so the build info is always detailed and based off the actual current tags.
=> git describe update

pkg/centos6/Dockerfile
namely, 
* we fail to install the scl command 
* continue to use python27 filename, despite installing python3 with pyenv
=> bugs with the centos6 pyenv changes

hubblestack/extmods/utils/s3.py
probably a typo from forward porting the rate limit fix into 4.0 branch.
=> some kind of conflict resolution typo most likely

hubblestack/utils/stdrec.py
Found a hubble_log message that was setting a bad value in the `host` field. This should fix that. Can we make sure this is merged into 4.0/develop?
=> Filter bad host values on queue log messages

hubblestack/extmods/fileserver/s3fs.py
Handles cached data correctly for s3fs if non 2XX response occurs.
=> Fix for cache bug in s3fs

hubblestack/extmods/fileserver/azurefs.py, hubblestack/utils/stdrec.py
'1a1b1c'.decode('hex') is now bytes.fromhex('1a1b1c'); conveniently, already bytes for b64encode()
=> 4.0 azure py3 fix and forward port of PR811

hubblestack/utils/signing.py
some really minor tweaks to mk-requirements.sh and utils/signing; though the utils/signing change prevents an annoying bug relating to (possibly) a configuration oddity... specifically, if we try to verify the signature of a `None` filename, `x=None; x.split('/')` fails
=> 4.0 polishing signing

pkg/centos8/Dockerfile, pkg/dev/centos8/Dockerfile
While installing build on centos-8, it shows conflict errors for some libraries. It got installed using --force flag. But, it is not a good practice.
There is a command change in building the rpm for centos-8 (fpm command) which resolves this issue.
=> build id changes for conflict

pkg/centos8/Dockerfile, pkg/dev/centos8/Dockerfile
double quotes needed to be escaped in the parameters.
=> Syntax error fix in command parameter to fpm

hubblestack/extmods/modules/nebula_osquery.py, pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/coreos/Dockerfile, pkg/debian10/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/osquery/Dockerfile
* include new Dockerfile for building osquery
* remove osquery build from all other Dockerfiles
* have augeas lens folder to be passed in by Hubble for snapshot queries
=> osquery dockerfiles and augeas folder fix

pkg/windows/hubble_config_permissions.ps1
- Earlier the permissions were set on '/etc/hubble' folder and they were making the effective permissions of 'hubble.conf' as 0. Changed the logic to have 'hubble.conf' same permissions as '/etc/hubble'.
=> Change in permissions for windows config file

hubblestack/extmods/modules/nebula_osquery.py
- Fixed bug in offset file creation for osquery that requires byte stream instead of str in python 3
=> Bug fix for python 2 to 3 migration in osquery offset file workflow

hubblestack/daemon.py, hubblestack/extmods/fileserver/azurefs.py, hubblestack/extmods/fileserver/roots.py, hubblestack/extmods/fileserver/s3fs.py, hubblestack/extmods/modules/nebula_osquery.py, hubblestack/extmods/modules/nova_loader.py, hubblestack/extmods/utils/gitfs.py, hubblestack/extmods/utils/s3.py, hubblestack/files/hubblestack_nova/firewall.py, hubblestack/grains/custom_grains_pillar.py, hubblestack/grains/default_gw.py, hubblestack/grains/disks.py, hubblestack/grains/extra.py, hubblestack/grains/fqdn.py, hubblestack/grains/hubble_core.py, hubblestack/grains/mdadm.py, hubblestack/grains/osqueryinfo.py, hubblestack/grains/systemuuid.py, hubblestack/grains/zfs.py, hubblestack/modules/cmdmod.py, hubblestack/utils/args.py, hubblestack/utils/data.py, hubblestack/utils/exceptions.py, hubblestack/utils/files.py, hubblestack/utils/path.py, hubblestack/utils/stringutils.py, hubblestack/utils/timed_subprocess.py
- moved salt.utils.stringutils to hubblestack.utils.stringutils
- Removed JinjaFilters as this is for some templating that we dont need
- moved salt.utils.path to hubblestack.utils.path
- moved salt.utils.args to hubblestack.utils.args
- moved salt.utils.data to hubblestack.utils.data
- moved salt.utils.files to hubblestack.utils.files
- Misc
- Added a new exception: HubbleInvocationError
- Added new encoding method in utils.__init__.py
- moved salt.modules.cmdmod.py to hubblestack.modules.cmdmod.py
- removed jinja templating code
- remove vt-terminal code
- moved salt.utils.timed_subprocess to hubblestack.utils.timed_subprocess
=> Salt-less Hubble Changes for 6 more libraries

hubblestack/grains/default_gw.py, hubblestack/grains/extra.py, hubblestack/grains/fqdn.py, hubblestack/grains/osqueryinfo.py, hubblestack/grains/zfs.py, hubblestack/utils/dictupdate.py, hubblestack/utils/odict.py, hubblestack/utils/stringutils.py, hubblestack/utils/yaml.py, hubblestack/utils/yamlloader.py, hubblestack/utils/zfs.py
This set completes all dependencies for grains.
- moved salt.utils.dictupdate to hubblestack.utils.dictupdate
- moved salt.utils.zfs to hubblestack.utils.zfs
- moved salt.utils.odict to hubblestack.utils.odict
- moved salt.utils.yaml to hubblestack.utils.yaml
- moved salt.utils.yamlloader to hubblestack.utils.yamlloader
=> Salt-less work - Bringing all dependencies for grains

hubblestack/utils/data.py, hubblestack/utils/files.py, hubblestack/utils/path.py, tests/support/helpers.py, tests/unittests/utils/test_args.py, tests/unittests/utils/test_data.py, tests/unittests/utils/test_files.py, tests/unittests/utils/test_path.py, tests/unittests/utils/test_stringutils.py
- moved test cases for salt.utils.files
- tests/unittests/utils/test_files.py
- moved test cases for salt.utils.data
- tests/unittests/utils/test_data.py
- moved test cases for salt.utils.args
- tests/unittests/utils/test_args.py
- moved test cases for salt.utils.path
- tests/unittests/utils/test_path.py
- moved test cases for salt.utils.stringutils
- tests/unittests/utils/test_stringutils.py
=> Salt-less work: Adding more test cases

hubblestack/extmods/fdg/command_line_parser.py, tests/unittests/test_command_line_parser.py
The module can be used to fetch value of keys provided in command lines. 
Example:
"dockerd --config-file=/etc/docker/daemon.json --log-level=debug"
In the above command line, the module can be used to fetch the value of `config-file` and `log-level`.
=> Adding FDG Command line parser module

hubblestack/extmods/modules/hubble.py
This took a sec to track down. I assumed at first it must be a problem with the data_list, but that was spurious -- I did leave some tuning in there anyway, but it's harmless.
The real problem was that since the dunder nova dict is a proper lazy loader and not a kludged loader, accessing the cache in the property under-dict is spurious now. The correct way is to iterate the items and keys of the dictionary itself.
=> Empty audit issue

hubblestack/daemon.py, hubblestack/loader.py
@Tenebriso and I were debugging something and discovered if a module exists in salt and in hubble, the salt module "wins" if the module isn't external ...
Turns out the paths the loader uses are most authoritative last, so any path occurring after hubble in the load list will overwrite what hubble is providing... so I reordered the paths to prefer hubble over salt.
I then taught the path type detector to return 'ext' for salt and 'int' for hubble ... and then relented and taught it to return 'salt' for salt, 'int' for hubble, and 'e_int' for old extmods/modules (eg) ...
So if you use `__mods__['test.ping']` you'll probably get `<function hubble.loaded.salt.module.test.ping()>`; and `__mods__['hubble.audit']` should give `<function hubble.loaded.e_int.module.hubble.audit…` ; and lastly, …
=> Minor loader changes

hubblestack/files/hubblestack_nova/fdg.py
Currently the nova connector does not work when the chaining is done using xpipe, because the return object is a list instead of a tuple. This code handles that workflow and consolidates the result when there are more than one item in the returned list. The supported consolidation operators are 'and' and 'or' and can be passes through the nova profile.
=> Nova connector consolidation

hubblestack/extmods/grains/cloud_details.py
- Fixed bug in fetching cloud account id and instance id in different clouds (AWS, Azure, GCP). Now an error will be logged and empty value is filled for that particular cloud, if there is any error or redirection for metadata URL.
- Changed order of calling metadata API for different clouds. Earlier, all cloud API's were called and only one of the present was expected to return the values. Now, the order of calls for clouds is as follows:
1.AWS
2.Azure
3.GCP
The calls will go to next cloud only when the current cloud is unable to provide instance metadata.
As this bug is impacting current releases as well as future releases, it needs to be back ported to 3.0 along with 4.0 branch.
Added logic to call a single API in GCP rather than calling multiple API.
=> Bug fix in cloud details grain in fetching instance metadata

hubblestack/daemon.py
Bug fix: Package list not getting refreshed
List of installed packages on a system is not refreshed in consecutive executions of Nova. As __context__ dictionary was being used to cache this result and was not being cleared.
=> Bug fix: Package list not getting refreshed

hubblestack/extmods/fdg/time_sync.py
The `NTPException` doesn't inherit from `Exception`, so it wouldn't be caught by the `except` in the case of a socket timeout, causing the test to fail sometimes.
=> fix time_sync

hubblestack/files/hubblestack_nova/win_gp.py, hubblestack/modules/win_system.py, tests/unittests/modules/test_win_system.py
I have found only one usage of the `system` module in the codebase, specifically the `win_system.get_domain_workgroup`. 
I don't know if we're using `modules/system.py` or `modules/mac_system.py` anywhere, but I will bring those in as well if we need them.
=> add win_system

hubblestack/loader.py
these are really minor changes to the namespaces (that nobody really uses) and some notes to remove things later.
=> mark these goofy namespaces for removal, and populate the rest of them

hubblestack/utils/signing.py, tests/unittests/conftest.py
We get crashes from empty profile pstat files pretty frequently. This repairs the problem.
After this merges and #936 rebases to develop, it should pass the annoying test failures it's having.
=> pytest_pyfunc_call is the wrong hook for prof.enable()

hubblestack/comparators/dict.py, hubblestack/comparators/list.py, tests/unittests/comparators/test_dict.py
1. There was a comparator in dictionary: match_any_if_key_matches whose name was confusing. It is renamed to match_any_if_keyvalue_matches
2. Fixing unit tests
=> Correcting behavior of match_any_if_keyvalue_matches and correcting unit tests

hubblestack/modules/cp.py
Adding cp.get_file function in salt's cp module.
Logs were showing this error not finding this function
=> Adding cp.get_file function in salt's cp module

hubblestack/modules/signing.py, hubblestack/utils/signing.py, tests/unittests/test_hs_config.py
1. modules signing.verify didn't know that it should look for a
CERTIFICATES file
2. utils.signing.X509 needs to check each extra_crt to see if it
has the basicConstraint.ca header set to true
=> changes to both modules.signing and utils.signing for intermediates in profiles

hubblestack/daemon.py
For some reason, the user config overrides (configs placed in hubble.d folder) are not working, this fixes that issue.
=> user config override issue

hubblestack/utils/signing.py
a couple minor problems and edge cases.
firstly, printing the cert filename was broken...
secondly, if you have a mixture of keys in RSA and ED25519, the ED25519 keys will fail after RSA keys due to a padding flag that shouldn't be passed in ED25519 `verify()` calls.
=> Signing problems

pkg/centos8/Dockerfile, pkg/debian8/Dockerfile
Build changes for Centos8 and Debian8
On CentOS-8, fpm 1.12 (latest) is broken. So 1.11 is being used.
For Debian8, its already EOL. And, to build Python >=3.7, we need to build openssl first.
=> Build changes for Centos8 and Debian8

hubblestack/daemon.py
We lost some serious dev time trying to figure out why the function didn't exist. It did, it was just producing a KeyError.
=> KeyError is a spurious way to detect loader keys

hubblestack/comparators/dict.py, hubblestack/utils/signing.py
This is a corner case where the value of **to_match_dict.get(key_name, None)** was **0 (zero)**, which is not **None**, but eventually python treats it as **`false`** and entered the if statement even when we did not wanted it to. Fixed it to explicitly enter the if statement only if the value is **None**
Also log_level is defined at a wrong place.
=> fixing bug

setup.py
On some platforms, azure was installed via requirements.txt at a specific version... on others, pip tried to isntall latest, which fails horribly becuase of py2.
(certes azure isn't the only thing that would fail...)
This PR simply makes setup.py use the same requirements as everything else.
=> why did some platforms fail on this and others did not? meh

.pipeline, package-requirements.txt, pkg/amazonlinux2016.09/entrypoint.sh, pkg/centos6/entrypoint.sh, pkg/centos7/entrypoint.sh, pkg/centos8/entrypoint.sh, pkg/coreos/entrypoint.sh, pkg/debian10/entrypoint.sh, pkg/debian8/entrypoint.sh, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/centos6/entrypoint.sh, pkg/dev/centos7/entrypoint.sh, pkg/dev/centos8/entrypoint.sh, pkg/dev/coreos/entrypoint.sh, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/entrypoint.sh, pkg/windows/Dockerfile, requirements.txt
Updating pip to latest version - 21.0.1 on all platforms
This is after the azurefs changes.
Now, we have the latest azurefs libraries, and the latest pip
For pyinstaller-hooks, now it comes pre-bundled with pyinstaller. No need for extra install.
=> Updating pip to latest version - 21.0.1 on all platforms

.gitignore, pkg/amazonlinux2016.09/Dockerfile, pkg/centos6/Dockerfile, pkg/centos7/Dockerfile, pkg/centos8/Dockerfile, pkg/debian10/Dockerfile, pkg/debian7/Dockerfile, pkg/debian8/Dockerfile, pkg/debian9/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/centos6/Dockerfile, pkg/dev/centos7/Dockerfile, pkg/dev/centos8/Dockerfile, pkg/dev/debian10/Dockerfile, pkg/dev/debian7/Dockerfile, pkg/dev/debian8/Dockerfile, pkg/dev/debian9/Dockerfile
* the most modern fpm won't install anywhere freeze at 1.11.0
* even at 1.11.0, ruby < 2.3 gets pretty miffed about linking to ffi in fpm; upgrade ruby on some platforms
* some of the packages get really angry about ascii locales (C, and Python both); try to use C.UTF-8 where possible, or give up and use en_US.UTF-8 (in one case)
=> More build fixes again

hubblestack/modules/signing.py, hubblestack/utils/signing.py
Example 
```
repo_signing:
require_verify: true
manifest_file_name: 'MANIFEST_v2'
signature_file_name: 'SIGNATURE_v2'
```
=> Manifest and signature filenames can be provided in config

hubblestack/grains/cloud_details.py
AWS Account IDs should be 12 digits long. This helps with leading zeros.
=> Pad AWS account ids to 12 digits

pkg/osquery/Dockerfile
For packaging newer version of osquery for next Hubble release.
=> Bump osquery to 4.6

hubblestack/utils/signing.py
It's very difficult to find documentation on `str.encode('charmap')` but it seems to want to use the character map of the environment locale. For `LANG=C` hosts, the charmap is "ascii" which breaks things using OpenSSL because of this `byte_string` function.
The only fix I can think of is to enforce UTF8 with a monkeypatch. We can't know if a host actually has any UTF-8 locales installed, so the best we can do is assume UTF-8 like whatever other module is sending UTF-8 characters through OpenSSL.
=> locale fix for LC_ALL=C/LANG=C hosts with no locales installed

tests/unittests/comparators/test_certificate.py
we were testing locale things and ran into failures in this test... cuz the magic date had past in number 4 test...
this should obviate that particular problem with the test
=> remove magic date strings

hubblestack/comparators/number.py
While comparing two integers, typecasting was required for module output.
=> Bug fix number comparator

hubblestack/modules/nebula_osquery.py, hubblestack/modules/pulsar.py, hubblestack/modules/signing.py, hubblestack/modules/win_pulsar.py, hubblestack/modules/win_pulsar_winaudit.py, hubblestack/utils/path.py, hubblestack/utils/signing.py, hubblestack/utils/timed_subprocess.py, requirements.txt, tests/unittests/test_repo_signing.py
* finish the thought in [#1029] and allow mfname and sfname to be fully configurable
* add an option allowing RSA salt-padding-bits to be configurable. The default is ('max', 32); meaning try 'max' (aka padding.PSS.MAX_LENGTH) first, and 32 bits as a fallback. Specifying `repo_signing: { salt_padding_bits: 'max' }` will disable the fallback
* add appropriate tests to make sure signing with 32 under (max, 32) and (32, max) works, that signing with 'max' under (max, 32) and (32, max) work; 
* and that 32-sign/check-max doesn't work and finally that signing max and checking 32 doesn't work.
* oh, and one final note that: this is only applicable under RSA. ECC doesn't have this padding issue as it's specified as part of the ECC protocol for the curve.
=> add setting to allow specifying salt-padding-bits in RSA

hubblestack/returners/splunk_audit_return.py, hubblestack/returners/splunk_fdg_return.py, hubblestack/returners/splunk_nebula_return.py, hubblestack/returners/splunk_nova_return.py, hubblestack/returners/splunk_osqueryd_return.py, hubblestack/returners/splunk_pulsar_return.py
* a handful of returns from fim and audit where presenting `null` fields in JSON (so, `None` in python); tell the key filter in each reterner to reject `None` in addition to `""`
=> patch all the returners to reject `None` in addition to `""`

hubblestack/files/hubblestack_nova/service.py, hubblestack/files/hubblestack_nova/systemctl.py, hubblestack/grains/cloud_details.py, requirements.txt
* grains should not generate log errors -- all hosts are missing something, we usually don't mention things we can't detect
* semi-unrelated logspam fix for minor nova processes: service.* is missing from `__mods__` on Docker processes. This shouldn't generate KeyError exceptions in the logs.
=> various log spam fixes

pkg/amazonlinux2016.09/entrypoint.sh, pkg/centos6/entrypoint.sh, pkg/centos7/entrypoint.sh, pkg/centos8/entrypoint.sh, pkg/coreos/entrypoint.sh, pkg/debian10/entrypoint.sh, pkg/debian8/entrypoint.sh, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/centos6/entrypoint.sh, pkg/dev/centos7/entrypoint.sh, pkg/dev/centos8/entrypoint.sh, pkg/dev/coreos/entrypoint.sh, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/entrypoint.sh
Debian packages won't install with `_` in their version number. Also, the version number is getting populated in rpms, debs, and other files as the actual tag (eg) `v4.5.0_rc4`; when it should be `4.5.0_rc4` or after this patch `4.5.0rc4`.
Probably the build args should get populated more correctly before this final docker step, but fixing it here won't hurt either.
=> version number fixes for versions based on checkout tags

hubblestack/modules/fdg.py
With this code change, both fdg versions can be used to execute profiles. If for example, **hubble fdg.run** is called, hubble will execute profiles kept in **salt://fdg/<profiles>** folder. 
Secondly, if hubble fdg.run fdg_version=fdg_v2 is called, then profiles kept in **salt://fdg_v2/<profiles>** are executed. The profiles in this folder need to be in new format.
Can be executed via hubble schedule as follows
`  fdg_top:
function: fdg.top
kwargs:
fdg_version: fdg_v2
seconds: 60
splay: 36
returner: splunk_fdg_return
run_on_start: True`
=> adding support for old fdg

hubblestack/modules/audit.py
this feels like a minor problem, but it means a missing file will necessarily cause any successful audit items ... to fail to actually return to splunk due to the stack trace.
=> if ret isn't a dict with stuff in it, don't loop through it

hubblestack/modules/audit.py, hubblestack/modules/fdg.py, hubblestack/utils/signing.py
fix some minor logging issues and avoid checking manifest/signature if they don't exist
=> Spurious utils.signing errors

hubblestack/fileserver/gitfs.py
This error looks spooky when you're looking for possibly related problems:
```
hubble.loaded.int.fi  INFO: no fileserver_backend configs, skipping gitfs                                              
```
It's also pretty misleading even if it were useful to spam it.
=> spooky unnecessary error message (on info channel)

hubblestack/audit/bexpr.py, hubblestack/audit/command_line_parser.py, hubblestack/audit/curl.py, hubblestack/audit/fdg.py, hubblestack/audit/grep.py, hubblestack/audit/misc.py, hubblestack/audit/osquery.py, hubblestack/audit/pkg.py, hubblestack/audit/readfile.py, hubblestack/audit/service.py, hubblestack/audit/ssl_certificate.py, hubblestack/audit/stat.py, hubblestack/audit/sysctl.py, hubblestack/audit/time_sync.py, hubblestack/audit/util.py, hubblestack/audit/win_auditpol.py, hubblestack/audit/win_firewall.py, hubblestack/audit/win_pkg.py, hubblestack/audit/win_reg.py, hubblestack/audit/win_secedit.py, hubblestack/module_runner/audit_runner.py, hubblestack/module_runner/runner.py
Adding a method in modules that can tell the audit runner what it was doing. This message can be then clubbed with failure reason from comparator to tell the user what actually failed on the system.
=> adding a method for fetching failure reason from module

hubblestack/grains/docker_details.py
This is a really minor thing, but I often test hubble without osquery installed... frequently I don't really care about the output, just the process details of daemon.py and the returners and things...
We get a pretty ungraceful crash if this needlessly checks the length of None; when a simple bool context would do the job.
=> check bool() not len() to avoid TypeError and for style points

hubblestack/utils/signing.py
This is meant as a speedup to the verification checking.
I don't think this was ever the source of very much slowdown, but it certainly does seem silly to verify signatures over and over and over for every file in the profile.
=> signing verification caching

hubblestack/module_runner/audit_runner.py, pkg/windows/Dockerfile
* The newer image of windows server is giving problem while building. Therefore using an old image that has been tested to be working.
Also, renamed the old check_id to check_unique_id and created a new key check_id that has the same value as old version of hubble
=> fixing windows build issue and adding check_unique_id key

pkg/windows/entrypoint.ps1
The package sha filename was incorrect. It should contain the version number.
=> correcting windows package sha filename

pkg/windows/Dockerfile, pkg/windows/hubble-Setup.nsi
* Not installing vcredist because it is only required in windows server 2008/ windows 7 and below. Also,
1. Reduces the build size by 6MBs, which is a 16.66% gain.
2. Greatly improves build time.
* updated osquery version from 3.4.0 to 4.6.0.2
=> not installing vcredist anymore, and updated osquery version in windows

pkg/windows/entrypoint.ps1
The dist folder gets created at a later stage when pyinstaller is run. Changing buildinfo before that now
=> fixing buildinfo not set issue

pkg/windows/entrypoint.ps1
The sha file name was changed, making the same change while copying
=> changed the sha name while copying

hubblestack/fileclient.py, hubblestack/fileserver/__init__.py, hubblestack/fileserver/roots.py, hubblestack/modules/cp.py, hubblestack/modules/hubble.py, hubblestack/utils/signing.py
For the record, the Elusive Signing Bug is a subtle bug where when a file fails the repo signing checks, it's still sometimes served to the code that was looking for it. It was extremely difficult to reproduce for some reason (even though some people could reproduce it every time).
I spent a horrific amount of time tracking this down. I finally determined that `cp.cache_dir` was never meant to be a proper sync. The original authors of hubble.audit.sync provided a `clean` argument that would `file.remove` the cache dir to prevent objects deleted from the repo sticking around after being elided.
The problem is that removing the whole cache and re-downloading it on every schedule loop is expensive, so someone disabled it later. It was probably thought that the regular …
=> I think this will sort out The Elusive Signing Bug

hubblestack/audit/misc.py
In hubble code, salt is now replaced by mods now.
=> removing salt from code

hubblestack/audit/win_secedit.py
Some values in security configuration like **MaximumPasswordAge** are values that are integers and do not have any reverse translation mapping. For these values, return only the actual value and not what was found in the configuration.
=> generalizing values that startswith 4,

hubblestack/audit/win_secedit.py
When **4,** is split, no matter what follows 4, there will always be at least 2 elements. Removing unnecessary if statement.
=> the length will always be at least 2

pkg/dev/amazonlinux2016.09/entrypoint.sh
Changes from PR - https://github.com/hubblestack/hubble/pull/1053 ported in dev build as well.
=> Amazon linux does not use systemd anymore

hubblestack/comparators/dict.py
In case the value type is string, it would error out. Instead pass the value as is and let the comparator take action.
=> not assuming that value is an int

pkg/README.md
The pkg folder contains files required to create hubble packages for all supported OSs. It also contains files required to create osquery package. The documentation helps the user understand what these files mean and how to use them.
=> Adding documentation for pkg folder

pkg/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2016.09/Dockerfile
sqlite3-devel was missing from the AL Dockerfile, which makes the sqlite returner fail to work, which causes some problems in automated testing.
=> oops sqlite3

hubblestack/fileserver/azurefs.py
Now the azure account url suffix can be passed from the config as well
=> Making the azure account url suffix configurable

hubblestack/fileclient.py
The extra '/' appended at the end of the path makes that path only linux specific, creating a problem for windows paths where '\' are used in paths instead of '/'. Not adding the extra '/' at the end of windows path works fine now.
=> fixing file caching bug in windows

hubblestack/files/hubblestack_nova/stat_nova.py
re-setting the value of mode because when reading profiles, the value is read as 0 and not 0000.
=> bug - value of 'mode' is read as 0 and not 0000

pkg/amazonlinux2016.09/Dockerfile, pkg/amazonlinux2016.09/entrypoint.sh, pkg/centos7/Dockerfile, pkg/centos7/entrypoint.sh, pkg/centos8/Dockerfile, pkg/centos8/entrypoint.sh, pkg/coreos/Dockerfile, pkg/coreos/entrypoint.sh, pkg/debian10/Dockerfile, pkg/debian10/entrypoint.sh, pkg/debian8/Dockerfile, pkg/debian8/entrypoint.sh, pkg/debian9/Dockerfile, pkg/debian9/entrypoint.sh, pkg/dev/amazonlinux2016.09/Dockerfile, pkg/dev/amazonlinux2016.09/entrypoint.sh, pkg/dev/centos7/Dockerfile, pkg/dev/centos7/entrypoint.sh, pkg/dev/centos8/Dockerfile, pkg/dev/centos8/entrypoint.sh, pkg/dev/coreos/Dockerfile, pkg/dev/coreos/entrypoint.sh, pkg/dev/debian10/Dockerfile, pkg/dev/debian10/entrypoint.sh, pkg/dev/debian8/Dockerfile, pkg/dev/debian8/entrypoint.sh, pkg/dev/debian9/Dockerfile, pkg/dev/debian9/entrypoint.sh
While building hubble pip throws error **pyenv init -` no longer sets PATH.** and is not installed.
=> pyenv init - no longer sets PATH.

.pre-commit-config.yaml
I also think we should use it starting like: immediately.
Turns out, we tore down the open source jenkins today.
=> update pre-commit. I think we should use this

hubblestack/daemon.py, hubblestack/loader.py, hubblestack/modules/conf_publisher.py, hubblestack/modules/nebula_osquery.py, setup.py
There's a few things here... not the least of which is a pretty obvious memory leak that we've had for as long as we've had grains-refresh...
The primary purpose of this PR is the 'POP' though. The persistent `__opts__` protection mechanism. It's definitely an anti-pattern that we're logging data by dropping it in config and publishing config... man, I wish we didn't do that, but we do it in a huge number of places. 
Recently, for some reason, the lazy loader refreshes have been resetting some of the `__opts__` return data. I can't see why it hadn't been doing it before now, but it's doing it now... so the solution -- until we address the anti-pattern -- is to trick the lazy loader into preserving __opts__.
Lastly, you may wonder: why is there no unit test to make sure this works?
This …
=> Loader fixes

pkg/windows/python_build/build_python.ps1
There was a simple but frustrating issue.
An environment variable was not there: %ProgramFiles(x86)%
Also put some checks around cleanup directories.
=> Build Python script changes for Windows FIPS

pkg/dev/rocky8/Dockerfile, pkg/rocky8/Dockerfile
The latest rocky linux 8 docker image has some issue that cannot resolve the current working directory in a docker container. Hence pinning the docker image to 8.4 ( a stable version released in June 2021).
=> Fixing Rocky dockerfile

hubblestack/fileclient.py
Formatting in MinionError references a a field 3, which should be a field 2.  May cause an exception if executed.
Note: the change-set is quite big due to linter requirements. The actual change is on line 691. Additionally, I've removed unused arguments on lines 44 and 260, respectively.
=> Fix logging formatting

hubblestack/grains/cloud_details.py
Lines 147 and 177, respectively, are where the update's been made. The rest is just linting.
=> Update azure version endpoint
